package com.vt.user.client;

import java.util.List;
import java.util.Map;

import com.vt.base.mapper.IBaseMapper;
import com.vt.user.model.Operator;
import com.vt.user.model.OperatorExample;
import com.vt.user.vo.OrgAndOperatorVO;
import com.vt.user.vo.RoleResOperVO;

public interface OperatorMapper   extends IBaseMapper<Operator, OperatorExample, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm_operator
     *
     * @mbggenerated Wed Nov 30 10:19:42 CST 2016
     */
    int countByExample(OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm_operator
     *
     * @mbggenerated Wed Nov 30 10:19:42 CST 2016
     */
    int deleteByPrimaryKey(Integer operatorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm_operator
     *
     * @mbggenerated Wed Nov 30 10:19:42 CST 2016
     */
    int insert(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm_operator
     *
     * @mbggenerated Wed Nov 30 10:19:42 CST 2016
     */
    int insertSelective(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm_operator
     *
     * @mbggenerated Wed Nov 30 10:19:42 CST 2016
     */
    List<Operator> selectByExample(OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm_operator
     *
     * @mbggenerated Wed Nov 30 10:19:42 CST 2016
     */
    Operator selectByPrimaryKey(Integer operatorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm_operator
     *
     * @mbggenerated Wed Nov 30 10:19:42 CST 2016
     */
    int updateByPrimaryKeySelective(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm_operator
     *
     * @mbggenerated Wed Nov 30 10:19:42 CST 2016
     */
    int updateByPrimaryKey(Operator record);
    
    List<OrgAndOperatorVO> selectOrgAndOptList(Operator operator);

    List<RoleResOperVO> selectRoleAndResList(Operator operator);
    
    List<Operator> queryUserIdsByRoleIdsAndOrgId(Map<String,Object> paramMap);
    
    List<Operator> queryOperatorListByRoleCode(Map<String,Object> paramMap);
    
}