package com.vt.fencing.model;

import java.util.List;
import java.util.Map;

public class ZlnfFoodInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FOODINFO.FMZT
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    private String fmzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FOODINFO.YORN
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    private String yorn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FOODINFO.FOODCODE
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    private String foodcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FOODINFO.FOODNAME
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    private String foodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FOODINFO.FOODNAMEJC
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    private String foodnamejc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FOODINFO.LINKNAME
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    private String linkname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FOODINFO.PHONE
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FOODINFO.CJSJ
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    private String cjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FOODINFO.ADDRESS
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FOODINFO.NBBM
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    private String nbbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FOODINFO.LKZZJGDM
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    private String lkzzjgdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FOODINFO.LNG
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FOODINFO.LAT
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FOODINFO.BUSYSTATE
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    private String busystate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FOODINFO.ISDELETED
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    private String isdeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FOODINFO.PROVICE
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    private String provice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FOODINFO.PROVICECODE
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    private String provicecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FOODINFO.CITY
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FOODINFO.CITYCODE
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    private String citycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FOODINFO.REMARKS
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    private String remarks;
    
    /**
     * 粮库历史记录对象
     */
    private List<ZlnfGraindepotHis> zlnfGraindepotHis;

    /**
     * 粮库最新记录对象
     */
    private List<ZlnfGraindepotNew> graindepotNewList;
    
    /**
     * 昨日收粮种类
     */
    private String yesterFoodKind;
    
    /**
     * 昨日收粮数量
     */
    private Double yesterGraindNum = (double) 0;

    /**
     * 昨日收粮价格
     */
    private Double yesterPrice = (double) 0;

    /**
     * 昨日收粮等级
     */
    private String yesterFoodlevel = "";

    /**
     * 昨日收粮水分
     */
    private Double yesterWater = (double) 0;

    /**
     * 今日收粮数量
     */
    private Double todayGraindNum = (double) 0;
    
    /**
     * 今日收粮价格
     */
    private Double todayPrice = (double) 0;

    /**
     * 今日收粮等级
     */
    private String todayLevel = "";

    /**
     * 今日收粮水分
     */
    private Double todayWater  = (double) 0;

    /**
     * 今日收粮种类
     */
    private String todayFoodkind = "";

    /**
     * 距离
     */
    private Double distance = (double) 0;

    /**
     * 之后7天预约卖粮信息
     */
    private List<Map<String, Object>> apppiontOrderTimeList;

    /**
     * 明日收粮种类
     */
    private String tomorrowFoodKind;
    
    /**
     * 明日收粮等级
     */
    private String tomorrowFoodlevel  = "";

    /**
     * 明日收粮价格
     */
    private Double tomorrowPrice = (double) 0;
    
    /**
     * 明日收粮水分
     */
    private Double tomorrowWater = (double) 0;
    
    /**
     * 卖粮记录
     */
    private List<ZlnfApppiontOrderTime> apppiontTimeList;

    /**
     * 粮库服务
     */
    private List<ZlnfFoodServiceInfo> foodServiceList;

    /**
     * 最大价格
     */
    private Double maxprice = (double) 0;
    
    /**
     * 最大数量
     */
    private Double maxnum = (double) 0;

    /**
     * 品种信息
     */
    private ZlnfDictInfo dictInfo;

    /**
     * 用户编号
     */
    private String usercode;

    /**
     * 类型
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FOODINFO.FMZT
     *
     * @return the value of ZLNF_FOODINFO.FMZT
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public String getFmzt() {
        return fmzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FOODINFO.FMZT
     *
     * @param fmzt the value for ZLNF_FOODINFO.FMZT
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public void setFmzt(String fmzt) {
        this.fmzt = fmzt == null ? null : fmzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FOODINFO.YORN
     *
     * @return the value of ZLNF_FOODINFO.YORN
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public String getYorn() {
        return yorn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FOODINFO.YORN
     *
     * @param yorn the value for ZLNF_FOODINFO.YORN
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public void setYorn(String yorn) {
        this.yorn = yorn == null ? null : yorn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FOODINFO.FOODCODE
     *
     * @return the value of ZLNF_FOODINFO.FOODCODE
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public String getFoodcode() {
        return foodcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FOODINFO.FOODCODE
     *
     * @param foodcode the value for ZLNF_FOODINFO.FOODCODE
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public void setFoodcode(String foodcode) {
        this.foodcode = foodcode == null ? null : foodcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FOODINFO.FOODNAME
     *
     * @return the value of ZLNF_FOODINFO.FOODNAME
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public String getFoodname() {
        return foodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FOODINFO.FOODNAME
     *
     * @param foodname the value for ZLNF_FOODINFO.FOODNAME
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public void setFoodname(String foodname) {
        this.foodname = foodname == null ? null : foodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FOODINFO.FOODNAMEJC
     *
     * @return the value of ZLNF_FOODINFO.FOODNAMEJC
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public String getFoodnamejc() {
        return foodnamejc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FOODINFO.FOODNAMEJC
     *
     * @param foodnamejc the value for ZLNF_FOODINFO.FOODNAMEJC
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public void setFoodnamejc(String foodnamejc) {
        this.foodnamejc = foodnamejc == null ? null : foodnamejc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FOODINFO.LINKNAME
     *
     * @return the value of ZLNF_FOODINFO.LINKNAME
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public String getLinkname() {
        return linkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FOODINFO.LINKNAME
     *
     * @param linkname the value for ZLNF_FOODINFO.LINKNAME
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public void setLinkname(String linkname) {
        this.linkname = linkname == null ? null : linkname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FOODINFO.PHONE
     *
     * @return the value of ZLNF_FOODINFO.PHONE
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FOODINFO.PHONE
     *
     * @param phone the value for ZLNF_FOODINFO.PHONE
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FOODINFO.CJSJ
     *
     * @return the value of ZLNF_FOODINFO.CJSJ
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public String getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FOODINFO.CJSJ
     *
     * @param cjsj the value for ZLNF_FOODINFO.CJSJ
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public void setCjsj(String cjsj) {
        this.cjsj = cjsj == null ? null : cjsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FOODINFO.ADDRESS
     *
     * @return the value of ZLNF_FOODINFO.ADDRESS
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FOODINFO.ADDRESS
     *
     * @param address the value for ZLNF_FOODINFO.ADDRESS
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FOODINFO.NBBM
     *
     * @return the value of ZLNF_FOODINFO.NBBM
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public String getNbbm() {
        return nbbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FOODINFO.NBBM
     *
     * @param nbbm the value for ZLNF_FOODINFO.NBBM
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public void setNbbm(String nbbm) {
        this.nbbm = nbbm == null ? null : nbbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FOODINFO.LKZZJGDM
     *
     * @return the value of ZLNF_FOODINFO.LKZZJGDM
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public String getLkzzjgdm() {
        return lkzzjgdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FOODINFO.LKZZJGDM
     *
     * @param lkzzjgdm the value for ZLNF_FOODINFO.LKZZJGDM
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public void setLkzzjgdm(String lkzzjgdm) {
        this.lkzzjgdm = lkzzjgdm == null ? null : lkzzjgdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FOODINFO.LNG
     *
     * @return the value of ZLNF_FOODINFO.LNG
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FOODINFO.LNG
     *
     * @param lng the value for ZLNF_FOODINFO.LNG
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FOODINFO.LAT
     *
     * @return the value of ZLNF_FOODINFO.LAT
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FOODINFO.LAT
     *
     * @param lat the value for ZLNF_FOODINFO.LAT
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FOODINFO.BUSYSTATE
     *
     * @return the value of ZLNF_FOODINFO.BUSYSTATE
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public String getBusystate() {
        return busystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FOODINFO.BUSYSTATE
     *
     * @param busystate the value for ZLNF_FOODINFO.BUSYSTATE
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public void setBusystate(String busystate) {
        this.busystate = busystate == null ? null : busystate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FOODINFO.ISDELETED
     *
     * @return the value of ZLNF_FOODINFO.ISDELETED
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public String getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FOODINFO.ISDELETED
     *
     * @param isdeleted the value for ZLNF_FOODINFO.ISDELETED
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public void setIsdeleted(String isdeleted) {
        this.isdeleted = isdeleted == null ? null : isdeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FOODINFO.PROVICE
     *
     * @return the value of ZLNF_FOODINFO.PROVICE
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public String getProvice() {
        return provice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FOODINFO.PROVICE
     *
     * @param provice the value for ZLNF_FOODINFO.PROVICE
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public void setProvice(String provice) {
        this.provice = provice == null ? null : provice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FOODINFO.PROVICECODE
     *
     * @return the value of ZLNF_FOODINFO.PROVICECODE
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public String getProvicecode() {
        return provicecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FOODINFO.PROVICECODE
     *
     * @param provicecode the value for ZLNF_FOODINFO.PROVICECODE
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public void setProvicecode(String provicecode) {
        this.provicecode = provicecode == null ? null : provicecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FOODINFO.CITY
     *
     * @return the value of ZLNF_FOODINFO.CITY
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FOODINFO.CITY
     *
     * @param city the value for ZLNF_FOODINFO.CITY
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FOODINFO.CITYCODE
     *
     * @return the value of ZLNF_FOODINFO.CITYCODE
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public String getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FOODINFO.CITYCODE
     *
     * @param citycode the value for ZLNF_FOODINFO.CITYCODE
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode == null ? null : citycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FOODINFO.REMARKS
     *
     * @return the value of ZLNF_FOODINFO.REMARKS
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FOODINFO.REMARKS
     *
     * @param remarks the value for ZLNF_FOODINFO.REMARKS
     *
     * @mbggenerated Wed Oct 18 17:09:31 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

	public List<ZlnfGraindepotHis> getZlnfGraindepotHis() {
		return zlnfGraindepotHis;
	}

	public void setZlnfGraindepotHis(List<ZlnfGraindepotHis> zlnfGraindepotHis) {
		this.zlnfGraindepotHis = zlnfGraindepotHis;
	}

	public List<ZlnfGraindepotNew> getGraindepotNewList() {
		return graindepotNewList;
	}

	public void setGraindepotNewList(List<ZlnfGraindepotNew> graindepotNewList) {
		this.graindepotNewList = graindepotNewList;
	}

	public String getYesterFoodKind() {
		return yesterFoodKind;
	}

	public void setYesterFoodKind(String yesterFoodKind) {
		this.yesterFoodKind = yesterFoodKind;
	}

	public Double getYesterGraindNum() {
		return yesterGraindNum;
	}

	public void setYesterGraindNum(Double yesterGraindNum) {
		this.yesterGraindNum = yesterGraindNum;
	}

	public Double getYesterPrice() {
		return yesterPrice;
	}

	public void setYesterPrice(Double yesterPrice) {
		this.yesterPrice = yesterPrice;
	}

	public String getYesterFoodlevel() {
		return yesterFoodlevel;
	}

	public void setYesterFoodlevel(String yesterFoodlevel) {
		this.yesterFoodlevel = yesterFoodlevel;
	}

	public Double getYesterWater() {
		return yesterWater;
	}

	public void setYesterWater(Double yesterWater) {
		this.yesterWater = yesterWater;
	}

	public Double getTodayGraindNum() {
		return todayGraindNum;
	}

	public void setTodayGraindNum(Double todayGraindNum) {
		this.todayGraindNum = todayGraindNum;
	}

	public Double getTodayPrice() {
		return todayPrice;
	}

	public void setTodayPrice(Double todayPrice) {
		this.todayPrice = todayPrice;
	}

	public String getTodayLevel() {
		return todayLevel;
	}

	public void setTodayLevel(String todayLevel) {
		this.todayLevel = todayLevel;
	}

	public Double getTodayWater() {
		return todayWater;
	}

	public void setTodayWater(Double todayWater) {
		this.todayWater = todayWater;
	}

	public String getTodayFoodkind() {
		return todayFoodkind;
	}

	public void setTodayFoodkind(String todayFoodkind) {
		this.todayFoodkind = todayFoodkind;
	}

	public Double getDistance() {
		return distance;
	}

	public void setDistance(Double distance) {
		this.distance = distance;
	}

	public List<Map<String, Object>> getApppiontOrderTimeList() {
		return apppiontOrderTimeList;
	}

	public void setApppiontOrderTimeList(
			List<Map<String, Object>> apppiontOrderTimeList) {
		this.apppiontOrderTimeList = apppiontOrderTimeList;
	}

	public String getTomorrowFoodKind() {
		return tomorrowFoodKind;
	}

	public void setTomorrowFoodKind(String tomorrowFoodKind) {
		this.tomorrowFoodKind = tomorrowFoodKind;
	}

	public String getTomorrowFoodlevel() {
		return tomorrowFoodlevel;
	}

	public void setTomorrowFoodlevel(String tomorrowFoodlevel) {
		this.tomorrowFoodlevel = tomorrowFoodlevel;
	}

	public Double getTomorrowPrice() {
		return tomorrowPrice;
	}

	public void setTomorrowPrice(Double tomorrowPrice) {
		this.tomorrowPrice = tomorrowPrice;
	}

	public Double getTomorrowWater() {
		return tomorrowWater;
	}

	public void setTomorrowWater(Double tomorrowWater) {
		this.tomorrowWater = tomorrowWater;
	}

	public List<ZlnfApppiontOrderTime> getApppiontTimeList() {
		return apppiontTimeList;
	}

	public void setApppiontTimeList(List<ZlnfApppiontOrderTime> apppiontTimeList) {
		this.apppiontTimeList = apppiontTimeList;
	}

	public List<ZlnfFoodServiceInfo> getFoodServiceList() {
		return foodServiceList;
	}

	public void setFoodServiceList(List<ZlnfFoodServiceInfo> foodServiceList) {
		this.foodServiceList = foodServiceList;
	}

	public Double getMaxprice() {
		return maxprice;
	}

	public void setMaxprice(Double maxprice) {
		this.maxprice = maxprice;
	}

	public Double getMaxnum() {
		return maxnum;
	}

	public void setMaxnum(Double maxnum) {
		this.maxnum = maxnum;
	}

	public ZlnfDictInfo getDictInfo() {
		return dictInfo;
	}

	public void setDictInfo(ZlnfDictInfo dictInfo) {
		this.dictInfo = dictInfo;
	}

	public String getUsercode() {
		return usercode;
	}

	public void setUsercode(String usercode) {
		this.usercode = usercode;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
}