package com.vt.fencing.model;

import java.util.Date;

public class ZlnfPaymenttypeCredit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_PAYMENTTYPE_CREDIT.ID
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_PAYMENTTYPE_CREDIT.ORDERCODE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    private String ordercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_PAYMENTTYPE_CREDIT.BILLCODE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    private String billcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_PAYMENTTYPE_CREDIT.PAYCODE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    private String paycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_PAYMENTTYPE_CREDIT.BILLDATE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    private Date billdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_PAYMENTTYPE_CREDIT.PAYDATE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    private Date paydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_PAYMENTTYPE_CREDIT.STATUS
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_PAYMENTTYPE_CREDIT.PAYACCOUNT
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    private String payaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_PAYMENTTYPE_CREDIT.PAYTYPE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    private String paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_PAYMENTTYPE_CREDIT.CREATOR
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_PAYMENTTYPE_CREDIT.CREATEDONUTC
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    private Date createdonutc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_PAYMENTTYPE_CREDIT.MODIFIER
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_PAYMENTTYPE_CREDIT.UPDATEDONUTC
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    private Date updatedonutc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_PAYMENTTYPE_CREDIT.HMPAY
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    private String hmpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_PAYMENTTYPE_CREDIT.ROLETYPE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    private String roletype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_PAYMENTTYPE_CREDIT.ROLECODE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    private String rolecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_PAYMENTTYPE_CREDIT.MODIFIERMC
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    private String modifiermc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_PAYMENTTYPE_CREDIT.REFUND
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    private Double refund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_PAYMENTTYPE_CREDIT.ORDERPAYTYPE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    private String orderpaytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_PAYMENTTYPE_CREDIT.STARTREFUNDDONUTC
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    private Date startrefunddonutc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_PAYMENTTYPE_CREDIT.REFUNDBAK
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    private Double refundbak;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_PAYMENTTYPE_CREDIT.ID
     *
     * @return the value of ZLNF_PAYMENTTYPE_CREDIT.ID
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_PAYMENTTYPE_CREDIT.ID
     *
     * @param id the value for ZLNF_PAYMENTTYPE_CREDIT.ID
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_PAYMENTTYPE_CREDIT.ORDERCODE
     *
     * @return the value of ZLNF_PAYMENTTYPE_CREDIT.ORDERCODE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public String getOrdercode() {
        return ordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_PAYMENTTYPE_CREDIT.ORDERCODE
     *
     * @param ordercode the value for ZLNF_PAYMENTTYPE_CREDIT.ORDERCODE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public void setOrdercode(String ordercode) {
        this.ordercode = ordercode == null ? null : ordercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_PAYMENTTYPE_CREDIT.BILLCODE
     *
     * @return the value of ZLNF_PAYMENTTYPE_CREDIT.BILLCODE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public String getBillcode() {
        return billcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_PAYMENTTYPE_CREDIT.BILLCODE
     *
     * @param billcode the value for ZLNF_PAYMENTTYPE_CREDIT.BILLCODE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public void setBillcode(String billcode) {
        this.billcode = billcode == null ? null : billcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_PAYMENTTYPE_CREDIT.PAYCODE
     *
     * @return the value of ZLNF_PAYMENTTYPE_CREDIT.PAYCODE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public String getPaycode() {
        return paycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_PAYMENTTYPE_CREDIT.PAYCODE
     *
     * @param paycode the value for ZLNF_PAYMENTTYPE_CREDIT.PAYCODE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public void setPaycode(String paycode) {
        this.paycode = paycode == null ? null : paycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_PAYMENTTYPE_CREDIT.BILLDATE
     *
     * @return the value of ZLNF_PAYMENTTYPE_CREDIT.BILLDATE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public Date getBilldate() {
        return billdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_PAYMENTTYPE_CREDIT.BILLDATE
     *
     * @param billdate the value for ZLNF_PAYMENTTYPE_CREDIT.BILLDATE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public void setBilldate(Date billdate) {
        this.billdate = billdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_PAYMENTTYPE_CREDIT.PAYDATE
     *
     * @return the value of ZLNF_PAYMENTTYPE_CREDIT.PAYDATE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public Date getPaydate() {
        return paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_PAYMENTTYPE_CREDIT.PAYDATE
     *
     * @param paydate the value for ZLNF_PAYMENTTYPE_CREDIT.PAYDATE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_PAYMENTTYPE_CREDIT.STATUS
     *
     * @return the value of ZLNF_PAYMENTTYPE_CREDIT.STATUS
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_PAYMENTTYPE_CREDIT.STATUS
     *
     * @param status the value for ZLNF_PAYMENTTYPE_CREDIT.STATUS
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_PAYMENTTYPE_CREDIT.PAYACCOUNT
     *
     * @return the value of ZLNF_PAYMENTTYPE_CREDIT.PAYACCOUNT
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public String getPayaccount() {
        return payaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_PAYMENTTYPE_CREDIT.PAYACCOUNT
     *
     * @param payaccount the value for ZLNF_PAYMENTTYPE_CREDIT.PAYACCOUNT
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public void setPayaccount(String payaccount) {
        this.payaccount = payaccount == null ? null : payaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_PAYMENTTYPE_CREDIT.PAYTYPE
     *
     * @return the value of ZLNF_PAYMENTTYPE_CREDIT.PAYTYPE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_PAYMENTTYPE_CREDIT.PAYTYPE
     *
     * @param paytype the value for ZLNF_PAYMENTTYPE_CREDIT.PAYTYPE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype == null ? null : paytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_PAYMENTTYPE_CREDIT.CREATOR
     *
     * @return the value of ZLNF_PAYMENTTYPE_CREDIT.CREATOR
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_PAYMENTTYPE_CREDIT.CREATOR
     *
     * @param creator the value for ZLNF_PAYMENTTYPE_CREDIT.CREATOR
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_PAYMENTTYPE_CREDIT.CREATEDONUTC
     *
     * @return the value of ZLNF_PAYMENTTYPE_CREDIT.CREATEDONUTC
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public Date getCreatedonutc() {
        return createdonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_PAYMENTTYPE_CREDIT.CREATEDONUTC
     *
     * @param createdonutc the value for ZLNF_PAYMENTTYPE_CREDIT.CREATEDONUTC
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public void setCreatedonutc(Date createdonutc) {
        this.createdonutc = createdonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_PAYMENTTYPE_CREDIT.MODIFIER
     *
     * @return the value of ZLNF_PAYMENTTYPE_CREDIT.MODIFIER
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_PAYMENTTYPE_CREDIT.MODIFIER
     *
     * @param modifier the value for ZLNF_PAYMENTTYPE_CREDIT.MODIFIER
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_PAYMENTTYPE_CREDIT.UPDATEDONUTC
     *
     * @return the value of ZLNF_PAYMENTTYPE_CREDIT.UPDATEDONUTC
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public Date getUpdatedonutc() {
        return updatedonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_PAYMENTTYPE_CREDIT.UPDATEDONUTC
     *
     * @param updatedonutc the value for ZLNF_PAYMENTTYPE_CREDIT.UPDATEDONUTC
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public void setUpdatedonutc(Date updatedonutc) {
        this.updatedonutc = updatedonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_PAYMENTTYPE_CREDIT.HMPAY
     *
     * @return the value of ZLNF_PAYMENTTYPE_CREDIT.HMPAY
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public String getHmpay() {
        return hmpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_PAYMENTTYPE_CREDIT.HMPAY
     *
     * @param hmpay the value for ZLNF_PAYMENTTYPE_CREDIT.HMPAY
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public void setHmpay(String hmpay) {
        this.hmpay = hmpay == null ? null : hmpay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_PAYMENTTYPE_CREDIT.ROLETYPE
     *
     * @return the value of ZLNF_PAYMENTTYPE_CREDIT.ROLETYPE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public String getRoletype() {
        return roletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_PAYMENTTYPE_CREDIT.ROLETYPE
     *
     * @param roletype the value for ZLNF_PAYMENTTYPE_CREDIT.ROLETYPE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public void setRoletype(String roletype) {
        this.roletype = roletype == null ? null : roletype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_PAYMENTTYPE_CREDIT.ROLECODE
     *
     * @return the value of ZLNF_PAYMENTTYPE_CREDIT.ROLECODE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_PAYMENTTYPE_CREDIT.ROLECODE
     *
     * @param rolecode the value for ZLNF_PAYMENTTYPE_CREDIT.ROLECODE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode == null ? null : rolecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_PAYMENTTYPE_CREDIT.MODIFIERMC
     *
     * @return the value of ZLNF_PAYMENTTYPE_CREDIT.MODIFIERMC
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public String getModifiermc() {
        return modifiermc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_PAYMENTTYPE_CREDIT.MODIFIERMC
     *
     * @param modifiermc the value for ZLNF_PAYMENTTYPE_CREDIT.MODIFIERMC
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public void setModifiermc(String modifiermc) {
        this.modifiermc = modifiermc == null ? null : modifiermc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_PAYMENTTYPE_CREDIT.REFUND
     *
     * @return the value of ZLNF_PAYMENTTYPE_CREDIT.REFUND
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public Double getRefund() {
        return refund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_PAYMENTTYPE_CREDIT.REFUND
     *
     * @param refund the value for ZLNF_PAYMENTTYPE_CREDIT.REFUND
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public void setRefund(Double refund) {
        this.refund = refund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_PAYMENTTYPE_CREDIT.ORDERPAYTYPE
     *
     * @return the value of ZLNF_PAYMENTTYPE_CREDIT.ORDERPAYTYPE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public String getOrderpaytype() {
        return orderpaytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_PAYMENTTYPE_CREDIT.ORDERPAYTYPE
     *
     * @param orderpaytype the value for ZLNF_PAYMENTTYPE_CREDIT.ORDERPAYTYPE
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public void setOrderpaytype(String orderpaytype) {
        this.orderpaytype = orderpaytype == null ? null : orderpaytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_PAYMENTTYPE_CREDIT.STARTREFUNDDONUTC
     *
     * @return the value of ZLNF_PAYMENTTYPE_CREDIT.STARTREFUNDDONUTC
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public Date getStartrefunddonutc() {
        return startrefunddonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_PAYMENTTYPE_CREDIT.STARTREFUNDDONUTC
     *
     * @param startrefunddonutc the value for ZLNF_PAYMENTTYPE_CREDIT.STARTREFUNDDONUTC
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public void setStartrefunddonutc(Date startrefunddonutc) {
        this.startrefunddonutc = startrefunddonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_PAYMENTTYPE_CREDIT.REFUNDBAK
     *
     * @return the value of ZLNF_PAYMENTTYPE_CREDIT.REFUNDBAK
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public Double getRefundbak() {
        return refundbak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_PAYMENTTYPE_CREDIT.REFUNDBAK
     *
     * @param refundbak the value for ZLNF_PAYMENTTYPE_CREDIT.REFUNDBAK
     *
     * @mbggenerated Tue Nov 28 10:59:30 CST 2017
     */
    public void setRefundbak(Double refundbak) {
        this.refundbak = refundbak;
    }
}