package com.vt.fencing.model;

import java.util.Date;

public class ZlnfFault {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FAULT.ID
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FAULT.FAULTCODE
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    private String faultcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FAULT.USERCODE
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    private String usercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FAULT.USERNAME
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FAULT.MOBILE
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FAULT.PHOTO
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FAULT.SOUNDRECORDING
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    private String soundrecording;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FAULT.DESCRIBE
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FAULT.STATUS
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FAULT.CREATOR
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FAULT.CREATEDONUTC
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    private Date createdonutc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FAULT.ISDELETED
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    private String isdeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FAULT.MODIFIER
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FAULT.UPDATEDONUTC
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    private Date updatedonutc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FAULT.ORDERCODE
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    private String ordercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_FAULT.VOICETIME
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    private String voicetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FAULT.ID
     *
     * @return the value of ZLNF_FAULT.ID
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FAULT.ID
     *
     * @param id the value for ZLNF_FAULT.ID
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FAULT.FAULTCODE
     *
     * @return the value of ZLNF_FAULT.FAULTCODE
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public String getFaultcode() {
        return faultcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FAULT.FAULTCODE
     *
     * @param faultcode the value for ZLNF_FAULT.FAULTCODE
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public void setFaultcode(String faultcode) {
        this.faultcode = faultcode == null ? null : faultcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FAULT.USERCODE
     *
     * @return the value of ZLNF_FAULT.USERCODE
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FAULT.USERCODE
     *
     * @param usercode the value for ZLNF_FAULT.USERCODE
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode == null ? null : usercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FAULT.USERNAME
     *
     * @return the value of ZLNF_FAULT.USERNAME
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FAULT.USERNAME
     *
     * @param username the value for ZLNF_FAULT.USERNAME
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FAULT.MOBILE
     *
     * @return the value of ZLNF_FAULT.MOBILE
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FAULT.MOBILE
     *
     * @param mobile the value for ZLNF_FAULT.MOBILE
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FAULT.PHOTO
     *
     * @return the value of ZLNF_FAULT.PHOTO
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FAULT.PHOTO
     *
     * @param photo the value for ZLNF_FAULT.PHOTO
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FAULT.SOUNDRECORDING
     *
     * @return the value of ZLNF_FAULT.SOUNDRECORDING
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public String getSoundrecording() {
        return soundrecording;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FAULT.SOUNDRECORDING
     *
     * @param soundrecording the value for ZLNF_FAULT.SOUNDRECORDING
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public void setSoundrecording(String soundrecording) {
        this.soundrecording = soundrecording == null ? null : soundrecording.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FAULT.DESCRIBE
     *
     * @return the value of ZLNF_FAULT.DESCRIBE
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FAULT.DESCRIBE
     *
     * @param describe the value for ZLNF_FAULT.DESCRIBE
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FAULT.STATUS
     *
     * @return the value of ZLNF_FAULT.STATUS
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FAULT.STATUS
     *
     * @param status the value for ZLNF_FAULT.STATUS
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FAULT.CREATOR
     *
     * @return the value of ZLNF_FAULT.CREATOR
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FAULT.CREATOR
     *
     * @param creator the value for ZLNF_FAULT.CREATOR
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FAULT.CREATEDONUTC
     *
     * @return the value of ZLNF_FAULT.CREATEDONUTC
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public Date getCreatedonutc() {
        return createdonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FAULT.CREATEDONUTC
     *
     * @param createdonutc the value for ZLNF_FAULT.CREATEDONUTC
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public void setCreatedonutc(Date createdonutc) {
        this.createdonutc = createdonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FAULT.ISDELETED
     *
     * @return the value of ZLNF_FAULT.ISDELETED
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public String getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FAULT.ISDELETED
     *
     * @param isdeleted the value for ZLNF_FAULT.ISDELETED
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public void setIsdeleted(String isdeleted) {
        this.isdeleted = isdeleted == null ? null : isdeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FAULT.MODIFIER
     *
     * @return the value of ZLNF_FAULT.MODIFIER
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FAULT.MODIFIER
     *
     * @param modifier the value for ZLNF_FAULT.MODIFIER
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FAULT.UPDATEDONUTC
     *
     * @return the value of ZLNF_FAULT.UPDATEDONUTC
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public Date getUpdatedonutc() {
        return updatedonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FAULT.UPDATEDONUTC
     *
     * @param updatedonutc the value for ZLNF_FAULT.UPDATEDONUTC
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public void setUpdatedonutc(Date updatedonutc) {
        this.updatedonutc = updatedonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FAULT.ORDERCODE
     *
     * @return the value of ZLNF_FAULT.ORDERCODE
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public String getOrdercode() {
        return ordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FAULT.ORDERCODE
     *
     * @param ordercode the value for ZLNF_FAULT.ORDERCODE
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public void setOrdercode(String ordercode) {
        this.ordercode = ordercode == null ? null : ordercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_FAULT.VOICETIME
     *
     * @return the value of ZLNF_FAULT.VOICETIME
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public String getVoicetime() {
        return voicetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_FAULT.VOICETIME
     *
     * @param voicetime the value for ZLNF_FAULT.VOICETIME
     *
     * @mbggenerated Fri Aug 25 15:41:45 CST 2017
     */
    public void setVoicetime(String voicetime) {
        this.voicetime = voicetime == null ? null : voicetime.trim();
    }
}