package com.vt.fencing.model;

import java.util.Date;

public class ZlnfLkorderDate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_LKORDER_DATE.BH
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    private String bh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_LKORDER_DATE.CJR
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    private String cjr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_LKORDER_DATE.CJSJ
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    private Date cjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_LKORDER_DATE.QS_DATE
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    private Date qsDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_LKORDER_DATE.JZ_DATE
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    private Date jzDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_LKORDER_DATE.BZ
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_LKORDER_DATE.CJRDW
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    private String cjrdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_LKORDER_DATE.CJRDWNBBM
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    private String cjrdwnbbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_LKORDER_DATE.CJRID
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    private String cjrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_LKORDER_DATE.ISDELETE
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    private String isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_LKORDER_DATE.FOODCODE
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    private String foodcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_LKORDER_DATE.BH
     *
     * @return the value of ZLNF_LKORDER_DATE.BH
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public String getBh() {
        return bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_LKORDER_DATE.BH
     *
     * @param bh the value for ZLNF_LKORDER_DATE.BH
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public void setBh(String bh) {
        this.bh = bh == null ? null : bh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_LKORDER_DATE.CJR
     *
     * @return the value of ZLNF_LKORDER_DATE.CJR
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public String getCjr() {
        return cjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_LKORDER_DATE.CJR
     *
     * @param cjr the value for ZLNF_LKORDER_DATE.CJR
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public void setCjr(String cjr) {
        this.cjr = cjr == null ? null : cjr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_LKORDER_DATE.CJSJ
     *
     * @return the value of ZLNF_LKORDER_DATE.CJSJ
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_LKORDER_DATE.CJSJ
     *
     * @param cjsj the value for ZLNF_LKORDER_DATE.CJSJ
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_LKORDER_DATE.QS_DATE
     *
     * @return the value of ZLNF_LKORDER_DATE.QS_DATE
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public Date getQsDate() {
        return qsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_LKORDER_DATE.QS_DATE
     *
     * @param qsDate the value for ZLNF_LKORDER_DATE.QS_DATE
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public void setQsDate(Date qsDate) {
        this.qsDate = qsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_LKORDER_DATE.JZ_DATE
     *
     * @return the value of ZLNF_LKORDER_DATE.JZ_DATE
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public Date getJzDate() {
        return jzDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_LKORDER_DATE.JZ_DATE
     *
     * @param jzDate the value for ZLNF_LKORDER_DATE.JZ_DATE
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public void setJzDate(Date jzDate) {
        this.jzDate = jzDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_LKORDER_DATE.BZ
     *
     * @return the value of ZLNF_LKORDER_DATE.BZ
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_LKORDER_DATE.BZ
     *
     * @param bz the value for ZLNF_LKORDER_DATE.BZ
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_LKORDER_DATE.CJRDW
     *
     * @return the value of ZLNF_LKORDER_DATE.CJRDW
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public String getCjrdw() {
        return cjrdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_LKORDER_DATE.CJRDW
     *
     * @param cjrdw the value for ZLNF_LKORDER_DATE.CJRDW
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public void setCjrdw(String cjrdw) {
        this.cjrdw = cjrdw == null ? null : cjrdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_LKORDER_DATE.CJRDWNBBM
     *
     * @return the value of ZLNF_LKORDER_DATE.CJRDWNBBM
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public String getCjrdwnbbm() {
        return cjrdwnbbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_LKORDER_DATE.CJRDWNBBM
     *
     * @param cjrdwnbbm the value for ZLNF_LKORDER_DATE.CJRDWNBBM
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public void setCjrdwnbbm(String cjrdwnbbm) {
        this.cjrdwnbbm = cjrdwnbbm == null ? null : cjrdwnbbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_LKORDER_DATE.CJRID
     *
     * @return the value of ZLNF_LKORDER_DATE.CJRID
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public String getCjrid() {
        return cjrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_LKORDER_DATE.CJRID
     *
     * @param cjrid the value for ZLNF_LKORDER_DATE.CJRID
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public void setCjrid(String cjrid) {
        this.cjrid = cjrid == null ? null : cjrid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_LKORDER_DATE.ISDELETE
     *
     * @return the value of ZLNF_LKORDER_DATE.ISDELETE
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public String getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_LKORDER_DATE.ISDELETE
     *
     * @param isdelete the value for ZLNF_LKORDER_DATE.ISDELETE
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete == null ? null : isdelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_LKORDER_DATE.FOODCODE
     *
     * @return the value of ZLNF_LKORDER_DATE.FOODCODE
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public String getFoodcode() {
        return foodcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_LKORDER_DATE.FOODCODE
     *
     * @param foodcode the value for ZLNF_LKORDER_DATE.FOODCODE
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    public void setFoodcode(String foodcode) {
        this.foodcode = foodcode == null ? null : foodcode.trim();
    }
}