package com.vt.fencing.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ZlnfBiDkzlDkzlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BI_DKZL_DKZL
     *
     * @mbggenerated Fri Nov 24 15:11:32 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BI_DKZL_DKZL
     *
     * @mbggenerated Fri Nov 24 15:11:32 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BI_DKZL_DKZL
     *
     * @mbggenerated Fri Nov 24 15:11:32 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_DKZL_DKZL
     *
     * @mbggenerated Fri Nov 24 15:11:32 CST 2017
     */
    public ZlnfBiDkzlDkzlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_DKZL_DKZL
     *
     * @mbggenerated Fri Nov 24 15:11:32 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_DKZL_DKZL
     *
     * @mbggenerated Fri Nov 24 15:11:32 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_DKZL_DKZL
     *
     * @mbggenerated Fri Nov 24 15:11:32 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_DKZL_DKZL
     *
     * @mbggenerated Fri Nov 24 15:11:32 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_DKZL_DKZL
     *
     * @mbggenerated Fri Nov 24 15:11:32 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_DKZL_DKZL
     *
     * @mbggenerated Fri Nov 24 15:11:32 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_DKZL_DKZL
     *
     * @mbggenerated Fri Nov 24 15:11:32 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_DKZL_DKZL
     *
     * @mbggenerated Fri Nov 24 15:11:32 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_DKZL_DKZL
     *
     * @mbggenerated Fri Nov 24 15:11:32 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_DKZL_DKZL
     *
     * @mbggenerated Fri Nov 24 15:11:32 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BI_DKZL_DKZL
     *
     * @mbggenerated Fri Nov 24 15:11:32 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCiLastupdateIsNull() {
            addCriterion("CI_LASTUPDATE is null");
            return (Criteria) this;
        }

        public Criteria andCiLastupdateIsNotNull() {
            addCriterion("CI_LASTUPDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCiLastupdateEqualTo(Date value) {
            addCriterion("CI_LASTUPDATE =", value, "ciLastupdate");
            return (Criteria) this;
        }

        public Criteria andCiLastupdateNotEqualTo(Date value) {
            addCriterion("CI_LASTUPDATE <>", value, "ciLastupdate");
            return (Criteria) this;
        }

        public Criteria andCiLastupdateGreaterThan(Date value) {
            addCriterion("CI_LASTUPDATE >", value, "ciLastupdate");
            return (Criteria) this;
        }

        public Criteria andCiLastupdateGreaterThanOrEqualTo(Date value) {
            addCriterion("CI_LASTUPDATE >=", value, "ciLastupdate");
            return (Criteria) this;
        }

        public Criteria andCiLastupdateLessThan(Date value) {
            addCriterion("CI_LASTUPDATE <", value, "ciLastupdate");
            return (Criteria) this;
        }

        public Criteria andCiLastupdateLessThanOrEqualTo(Date value) {
            addCriterion("CI_LASTUPDATE <=", value, "ciLastupdate");
            return (Criteria) this;
        }

        public Criteria andCiLastupdateIn(List<Date> values) {
            addCriterion("CI_LASTUPDATE in", values, "ciLastupdate");
            return (Criteria) this;
        }

        public Criteria andCiLastupdateNotIn(List<Date> values) {
            addCriterion("CI_LASTUPDATE not in", values, "ciLastupdate");
            return (Criteria) this;
        }

        public Criteria andCiLastupdateBetween(Date value1, Date value2) {
            addCriterion("CI_LASTUPDATE between", value1, value2, "ciLastupdate");
            return (Criteria) this;
        }

        public Criteria andCiLastupdateNotBetween(Date value1, Date value2) {
            addCriterion("CI_LASTUPDATE not between", value1, value2, "ciLastupdate");
            return (Criteria) this;
        }

        public Criteria andCiLastuptimeIsNull() {
            addCriterion("CI_LASTUPTIME is null");
            return (Criteria) this;
        }

        public Criteria andCiLastuptimeIsNotNull() {
            addCriterion("CI_LASTUPTIME is not null");
            return (Criteria) this;
        }

        public Criteria andCiLastuptimeEqualTo(BigDecimal value) {
            addCriterion("CI_LASTUPTIME =", value, "ciLastuptime");
            return (Criteria) this;
        }

        public Criteria andCiLastuptimeNotEqualTo(BigDecimal value) {
            addCriterion("CI_LASTUPTIME <>", value, "ciLastuptime");
            return (Criteria) this;
        }

        public Criteria andCiLastuptimeGreaterThan(BigDecimal value) {
            addCriterion("CI_LASTUPTIME >", value, "ciLastuptime");
            return (Criteria) this;
        }

        public Criteria andCiLastuptimeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CI_LASTUPTIME >=", value, "ciLastuptime");
            return (Criteria) this;
        }

        public Criteria andCiLastuptimeLessThan(BigDecimal value) {
            addCriterion("CI_LASTUPTIME <", value, "ciLastuptime");
            return (Criteria) this;
        }

        public Criteria andCiLastuptimeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CI_LASTUPTIME <=", value, "ciLastuptime");
            return (Criteria) this;
        }

        public Criteria andCiLastuptimeIn(List<BigDecimal> values) {
            addCriterion("CI_LASTUPTIME in", values, "ciLastuptime");
            return (Criteria) this;
        }

        public Criteria andCiLastuptimeNotIn(List<BigDecimal> values) {
            addCriterion("CI_LASTUPTIME not in", values, "ciLastuptime");
            return (Criteria) this;
        }

        public Criteria andCiLastuptimeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CI_LASTUPTIME between", value1, value2, "ciLastuptime");
            return (Criteria) this;
        }

        public Criteria andCiLastuptimeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CI_LASTUPTIME not between", value1, value2, "ciLastuptime");
            return (Criteria) this;
        }

        public Criteria andCiAudittagIsNull() {
            addCriterion("CI_AUDITTAG is null");
            return (Criteria) this;
        }

        public Criteria andCiAudittagIsNotNull() {
            addCriterion("CI_AUDITTAG is not null");
            return (Criteria) this;
        }

        public Criteria andCiAudittagEqualTo(Long value) {
            addCriterion("CI_AUDITTAG =", value, "ciAudittag");
            return (Criteria) this;
        }

        public Criteria andCiAudittagNotEqualTo(Long value) {
            addCriterion("CI_AUDITTAG <>", value, "ciAudittag");
            return (Criteria) this;
        }

        public Criteria andCiAudittagGreaterThan(Long value) {
            addCriterion("CI_AUDITTAG >", value, "ciAudittag");
            return (Criteria) this;
        }

        public Criteria andCiAudittagGreaterThanOrEqualTo(Long value) {
            addCriterion("CI_AUDITTAG >=", value, "ciAudittag");
            return (Criteria) this;
        }

        public Criteria andCiAudittagLessThan(Long value) {
            addCriterion("CI_AUDITTAG <", value, "ciAudittag");
            return (Criteria) this;
        }

        public Criteria andCiAudittagLessThanOrEqualTo(Long value) {
            addCriterion("CI_AUDITTAG <=", value, "ciAudittag");
            return (Criteria) this;
        }

        public Criteria andCiAudittagIn(List<Long> values) {
            addCriterion("CI_AUDITTAG in", values, "ciAudittag");
            return (Criteria) this;
        }

        public Criteria andCiAudittagNotIn(List<Long> values) {
            addCriterion("CI_AUDITTAG not in", values, "ciAudittag");
            return (Criteria) this;
        }

        public Criteria andCiAudittagBetween(Long value1, Long value2) {
            addCriterion("CI_AUDITTAG between", value1, value2, "ciAudittag");
            return (Criteria) this;
        }

        public Criteria andCiAudittagNotBetween(Long value1, Long value2) {
            addCriterion("CI_AUDITTAG not between", value1, value2, "ciAudittag");
            return (Criteria) this;
        }

        public Criteria andDkzlIsNull() {
            addCriterion("DKZL is null");
            return (Criteria) this;
        }

        public Criteria andDkzlIsNotNull() {
            addCriterion("DKZL is not null");
            return (Criteria) this;
        }

        public Criteria andDkzlEqualTo(String value) {
            addCriterion("DKZL =", value, "dkzl");
            return (Criteria) this;
        }

        public Criteria andDkzlNotEqualTo(String value) {
            addCriterion("DKZL <>", value, "dkzl");
            return (Criteria) this;
        }

        public Criteria andDkzlGreaterThan(String value) {
            addCriterion("DKZL >", value, "dkzl");
            return (Criteria) this;
        }

        public Criteria andDkzlGreaterThanOrEqualTo(String value) {
            addCriterion("DKZL >=", value, "dkzl");
            return (Criteria) this;
        }

        public Criteria andDkzlLessThan(String value) {
            addCriterion("DKZL <", value, "dkzl");
            return (Criteria) this;
        }

        public Criteria andDkzlLessThanOrEqualTo(String value) {
            addCriterion("DKZL <=", value, "dkzl");
            return (Criteria) this;
        }

        public Criteria andDkzlLike(String value) {
            addCriterion("DKZL like", value, "dkzl");
            return (Criteria) this;
        }

        public Criteria andDkzlNotLike(String value) {
            addCriterion("DKZL not like", value, "dkzl");
            return (Criteria) this;
        }

        public Criteria andDkzlIn(List<String> values) {
            addCriterion("DKZL in", values, "dkzl");
            return (Criteria) this;
        }

        public Criteria andDkzlNotIn(List<String> values) {
            addCriterion("DKZL not in", values, "dkzl");
            return (Criteria) this;
        }

        public Criteria andDkzlBetween(String value1, String value2) {
            addCriterion("DKZL between", value1, value2, "dkzl");
            return (Criteria) this;
        }

        public Criteria andDkzlNotBetween(String value1, String value2) {
            addCriterion("DKZL not between", value1, value2, "dkzl");
            return (Criteria) this;
        }

        public Criteria andDksmIsNull() {
            addCriterion("DKSM is null");
            return (Criteria) this;
        }

        public Criteria andDksmIsNotNull() {
            addCriterion("DKSM is not null");
            return (Criteria) this;
        }

        public Criteria andDksmEqualTo(String value) {
            addCriterion("DKSM =", value, "dksm");
            return (Criteria) this;
        }

        public Criteria andDksmNotEqualTo(String value) {
            addCriterion("DKSM <>", value, "dksm");
            return (Criteria) this;
        }

        public Criteria andDksmGreaterThan(String value) {
            addCriterion("DKSM >", value, "dksm");
            return (Criteria) this;
        }

        public Criteria andDksmGreaterThanOrEqualTo(String value) {
            addCriterion("DKSM >=", value, "dksm");
            return (Criteria) this;
        }

        public Criteria andDksmLessThan(String value) {
            addCriterion("DKSM <", value, "dksm");
            return (Criteria) this;
        }

        public Criteria andDksmLessThanOrEqualTo(String value) {
            addCriterion("DKSM <=", value, "dksm");
            return (Criteria) this;
        }

        public Criteria andDksmLike(String value) {
            addCriterion("DKSM like", value, "dksm");
            return (Criteria) this;
        }

        public Criteria andDksmNotLike(String value) {
            addCriterion("DKSM not like", value, "dksm");
            return (Criteria) this;
        }

        public Criteria andDksmIn(List<String> values) {
            addCriterion("DKSM in", values, "dksm");
            return (Criteria) this;
        }

        public Criteria andDksmNotIn(List<String> values) {
            addCriterion("DKSM not in", values, "dksm");
            return (Criteria) this;
        }

        public Criteria andDksmBetween(String value1, String value2) {
            addCriterion("DKSM between", value1, value2, "dksm");
            return (Criteria) this;
        }

        public Criteria andDksmNotBetween(String value1, String value2) {
            addCriterion("DKSM not between", value1, value2, "dksm");
            return (Criteria) this;
        }

        public Criteria andCjrbmIsNull() {
            addCriterion("CJRBM is null");
            return (Criteria) this;
        }

        public Criteria andCjrbmIsNotNull() {
            addCriterion("CJRBM is not null");
            return (Criteria) this;
        }

        public Criteria andCjrbmEqualTo(String value) {
            addCriterion("CJRBM =", value, "cjrbm");
            return (Criteria) this;
        }

        public Criteria andCjrbmNotEqualTo(String value) {
            addCriterion("CJRBM <>", value, "cjrbm");
            return (Criteria) this;
        }

        public Criteria andCjrbmGreaterThan(String value) {
            addCriterion("CJRBM >", value, "cjrbm");
            return (Criteria) this;
        }

        public Criteria andCjrbmGreaterThanOrEqualTo(String value) {
            addCriterion("CJRBM >=", value, "cjrbm");
            return (Criteria) this;
        }

        public Criteria andCjrbmLessThan(String value) {
            addCriterion("CJRBM <", value, "cjrbm");
            return (Criteria) this;
        }

        public Criteria andCjrbmLessThanOrEqualTo(String value) {
            addCriterion("CJRBM <=", value, "cjrbm");
            return (Criteria) this;
        }

        public Criteria andCjrbmLike(String value) {
            addCriterion("CJRBM like", value, "cjrbm");
            return (Criteria) this;
        }

        public Criteria andCjrbmNotLike(String value) {
            addCriterion("CJRBM not like", value, "cjrbm");
            return (Criteria) this;
        }

        public Criteria andCjrbmIn(List<String> values) {
            addCriterion("CJRBM in", values, "cjrbm");
            return (Criteria) this;
        }

        public Criteria andCjrbmNotIn(List<String> values) {
            addCriterion("CJRBM not in", values, "cjrbm");
            return (Criteria) this;
        }

        public Criteria andCjrbmBetween(String value1, String value2) {
            addCriterion("CJRBM between", value1, value2, "cjrbm");
            return (Criteria) this;
        }

        public Criteria andCjrbmNotBetween(String value1, String value2) {
            addCriterion("CJRBM not between", value1, value2, "cjrbm");
            return (Criteria) this;
        }

        public Criteria andUuidIsNull() {
            addCriterion("UUID is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("UUID is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("UUID =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("UUID <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("UUID >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("UUID >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("UUID <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("UUID <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("UUID like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("UUID not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("UUID in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("UUID not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("UUID between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("UUID not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andCjrIsNull() {
            addCriterion("CJR is null");
            return (Criteria) this;
        }

        public Criteria andCjrIsNotNull() {
            addCriterion("CJR is not null");
            return (Criteria) this;
        }

        public Criteria andCjrEqualTo(String value) {
            addCriterion("CJR =", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrNotEqualTo(String value) {
            addCriterion("CJR <>", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrGreaterThan(String value) {
            addCriterion("CJR >", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrGreaterThanOrEqualTo(String value) {
            addCriterion("CJR >=", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrLessThan(String value) {
            addCriterion("CJR <", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrLessThanOrEqualTo(String value) {
            addCriterion("CJR <=", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrLike(String value) {
            addCriterion("CJR like", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrNotLike(String value) {
            addCriterion("CJR not like", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrIn(List<String> values) {
            addCriterion("CJR in", values, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrNotIn(List<String> values) {
            addCriterion("CJR not in", values, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrBetween(String value1, String value2) {
            addCriterion("CJR between", value1, value2, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrNotBetween(String value1, String value2) {
            addCriterion("CJR not between", value1, value2, "cjr");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIsNull() {
            addCriterion("ISDELETED is null");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIsNotNull() {
            addCriterion("ISDELETED is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeletedEqualTo(String value) {
            addCriterion("ISDELETED =", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotEqualTo(String value) {
            addCriterion("ISDELETED <>", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedGreaterThan(String value) {
            addCriterion("ISDELETED >", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedGreaterThanOrEqualTo(String value) {
            addCriterion("ISDELETED >=", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLessThan(String value) {
            addCriterion("ISDELETED <", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLessThanOrEqualTo(String value) {
            addCriterion("ISDELETED <=", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLike(String value) {
            addCriterion("ISDELETED like", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotLike(String value) {
            addCriterion("ISDELETED not like", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIn(List<String> values) {
            addCriterion("ISDELETED in", values, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotIn(List<String> values) {
            addCriterion("ISDELETED not in", values, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedBetween(String value1, String value2) {
            addCriterion("ISDELETED between", value1, value2, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotBetween(String value1, String value2) {
            addCriterion("ISDELETED not between", value1, value2, "isdeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BI_DKZL_DKZL
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 24 15:11:32 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BI_DKZL_DKZL
     *
     * @mbggenerated Fri Nov 24 15:11:32 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}