package com.vt.fencing.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ZlnfFarmmachineyUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZLNF_FARMMACHINEYUSER
     *
     * @mbggenerated Tue Jul 18 15:49:26 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZLNF_FARMMACHINEYUSER
     *
     * @mbggenerated Tue Jul 18 15:49:26 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZLNF_FARMMACHINEYUSER
     *
     * @mbggenerated Tue Jul 18 15:49:26 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_FARMMACHINEYUSER
     *
     * @mbggenerated Tue Jul 18 15:49:26 CST 2017
     */
    public ZlnfFarmmachineyUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_FARMMACHINEYUSER
     *
     * @mbggenerated Tue Jul 18 15:49:26 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_FARMMACHINEYUSER
     *
     * @mbggenerated Tue Jul 18 15:49:26 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_FARMMACHINEYUSER
     *
     * @mbggenerated Tue Jul 18 15:49:26 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_FARMMACHINEYUSER
     *
     * @mbggenerated Tue Jul 18 15:49:26 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_FARMMACHINEYUSER
     *
     * @mbggenerated Tue Jul 18 15:49:26 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_FARMMACHINEYUSER
     *
     * @mbggenerated Tue Jul 18 15:49:26 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_FARMMACHINEYUSER
     *
     * @mbggenerated Tue Jul 18 15:49:26 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_FARMMACHINEYUSER
     *
     * @mbggenerated Tue Jul 18 15:49:26 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_FARMMACHINEYUSER
     *
     * @mbggenerated Tue Jul 18 15:49:26 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_FARMMACHINEYUSER
     *
     * @mbggenerated Tue Jul 18 15:49:26 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ZLNF_FARMMACHINEYUSER
     *
     * @mbggenerated Tue Jul 18 15:49:26 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUsercodeIsNull() {
            addCriterion("USERCODE is null");
            return (Criteria) this;
        }

        public Criteria andUsercodeIsNotNull() {
            addCriterion("USERCODE is not null");
            return (Criteria) this;
        }

        public Criteria andUsercodeEqualTo(String value) {
            addCriterion("USERCODE =", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeNotEqualTo(String value) {
            addCriterion("USERCODE <>", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeGreaterThan(String value) {
            addCriterion("USERCODE >", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeGreaterThanOrEqualTo(String value) {
            addCriterion("USERCODE >=", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeLessThan(String value) {
            addCriterion("USERCODE <", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeLessThanOrEqualTo(String value) {
            addCriterion("USERCODE <=", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeLike(String value) {
            addCriterion("USERCODE like", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeNotLike(String value) {
            addCriterion("USERCODE not like", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeIn(List<String> values) {
            addCriterion("USERCODE in", values, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeNotIn(List<String> values) {
            addCriterion("USERCODE not in", values, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeBetween(String value1, String value2) {
            addCriterion("USERCODE between", value1, value2, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeNotBetween(String value1, String value2) {
            addCriterion("USERCODE not between", value1, value2, "usercode");
            return (Criteria) this;
        }

        public Criteria andFarmmachineynameIsNull() {
            addCriterion("FARMMACHINEYNAME is null");
            return (Criteria) this;
        }

        public Criteria andFarmmachineynameIsNotNull() {
            addCriterion("FARMMACHINEYNAME is not null");
            return (Criteria) this;
        }

        public Criteria andFarmmachineynameEqualTo(String value) {
            addCriterion("FARMMACHINEYNAME =", value, "farmmachineyname");
            return (Criteria) this;
        }

        public Criteria andFarmmachineynameNotEqualTo(String value) {
            addCriterion("FARMMACHINEYNAME <>", value, "farmmachineyname");
            return (Criteria) this;
        }

        public Criteria andFarmmachineynameGreaterThan(String value) {
            addCriterion("FARMMACHINEYNAME >", value, "farmmachineyname");
            return (Criteria) this;
        }

        public Criteria andFarmmachineynameGreaterThanOrEqualTo(String value) {
            addCriterion("FARMMACHINEYNAME >=", value, "farmmachineyname");
            return (Criteria) this;
        }

        public Criteria andFarmmachineynameLessThan(String value) {
            addCriterion("FARMMACHINEYNAME <", value, "farmmachineyname");
            return (Criteria) this;
        }

        public Criteria andFarmmachineynameLessThanOrEqualTo(String value) {
            addCriterion("FARMMACHINEYNAME <=", value, "farmmachineyname");
            return (Criteria) this;
        }

        public Criteria andFarmmachineynameLike(String value) {
            addCriterion("FARMMACHINEYNAME like", value, "farmmachineyname");
            return (Criteria) this;
        }

        public Criteria andFarmmachineynameNotLike(String value) {
            addCriterion("FARMMACHINEYNAME not like", value, "farmmachineyname");
            return (Criteria) this;
        }

        public Criteria andFarmmachineynameIn(List<String> values) {
            addCriterion("FARMMACHINEYNAME in", values, "farmmachineyname");
            return (Criteria) this;
        }

        public Criteria andFarmmachineynameNotIn(List<String> values) {
            addCriterion("FARMMACHINEYNAME not in", values, "farmmachineyname");
            return (Criteria) this;
        }

        public Criteria andFarmmachineynameBetween(String value1, String value2) {
            addCriterion("FARMMACHINEYNAME between", value1, value2, "farmmachineyname");
            return (Criteria) this;
        }

        public Criteria andFarmmachineynameNotBetween(String value1, String value2) {
            addCriterion("FARMMACHINEYNAME not between", value1, value2, "farmmachineyname");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andRoletypeIsNull() {
            addCriterion("ROLETYPE is null");
            return (Criteria) this;
        }

        public Criteria andRoletypeIsNotNull() {
            addCriterion("ROLETYPE is not null");
            return (Criteria) this;
        }

        public Criteria andRoletypeEqualTo(String value) {
            addCriterion("ROLETYPE =", value, "roletype");
            return (Criteria) this;
        }

        public Criteria andRoletypeNotEqualTo(String value) {
            addCriterion("ROLETYPE <>", value, "roletype");
            return (Criteria) this;
        }

        public Criteria andRoletypeGreaterThan(String value) {
            addCriterion("ROLETYPE >", value, "roletype");
            return (Criteria) this;
        }

        public Criteria andRoletypeGreaterThanOrEqualTo(String value) {
            addCriterion("ROLETYPE >=", value, "roletype");
            return (Criteria) this;
        }

        public Criteria andRoletypeLessThan(String value) {
            addCriterion("ROLETYPE <", value, "roletype");
            return (Criteria) this;
        }

        public Criteria andRoletypeLessThanOrEqualTo(String value) {
            addCriterion("ROLETYPE <=", value, "roletype");
            return (Criteria) this;
        }

        public Criteria andRoletypeLike(String value) {
            addCriterion("ROLETYPE like", value, "roletype");
            return (Criteria) this;
        }

        public Criteria andRoletypeNotLike(String value) {
            addCriterion("ROLETYPE not like", value, "roletype");
            return (Criteria) this;
        }

        public Criteria andRoletypeIn(List<String> values) {
            addCriterion("ROLETYPE in", values, "roletype");
            return (Criteria) this;
        }

        public Criteria andRoletypeNotIn(List<String> values) {
            addCriterion("ROLETYPE not in", values, "roletype");
            return (Criteria) this;
        }

        public Criteria andRoletypeBetween(String value1, String value2) {
            addCriterion("ROLETYPE between", value1, value2, "roletype");
            return (Criteria) this;
        }

        public Criteria andRoletypeNotBetween(String value1, String value2) {
            addCriterion("ROLETYPE not between", value1, value2, "roletype");
            return (Criteria) this;
        }

        public Criteria andFarmmachineycodeIsNull() {
            addCriterion("FARMMACHINEYCODE is null");
            return (Criteria) this;
        }

        public Criteria andFarmmachineycodeIsNotNull() {
            addCriterion("FARMMACHINEYCODE is not null");
            return (Criteria) this;
        }

        public Criteria andFarmmachineycodeEqualTo(String value) {
            addCriterion("FARMMACHINEYCODE =", value, "farmmachineycode");
            return (Criteria) this;
        }

        public Criteria andFarmmachineycodeNotEqualTo(String value) {
            addCriterion("FARMMACHINEYCODE <>", value, "farmmachineycode");
            return (Criteria) this;
        }

        public Criteria andFarmmachineycodeGreaterThan(String value) {
            addCriterion("FARMMACHINEYCODE >", value, "farmmachineycode");
            return (Criteria) this;
        }

        public Criteria andFarmmachineycodeGreaterThanOrEqualTo(String value) {
            addCriterion("FARMMACHINEYCODE >=", value, "farmmachineycode");
            return (Criteria) this;
        }

        public Criteria andFarmmachineycodeLessThan(String value) {
            addCriterion("FARMMACHINEYCODE <", value, "farmmachineycode");
            return (Criteria) this;
        }

        public Criteria andFarmmachineycodeLessThanOrEqualTo(String value) {
            addCriterion("FARMMACHINEYCODE <=", value, "farmmachineycode");
            return (Criteria) this;
        }

        public Criteria andFarmmachineycodeLike(String value) {
            addCriterion("FARMMACHINEYCODE like", value, "farmmachineycode");
            return (Criteria) this;
        }

        public Criteria andFarmmachineycodeNotLike(String value) {
            addCriterion("FARMMACHINEYCODE not like", value, "farmmachineycode");
            return (Criteria) this;
        }

        public Criteria andFarmmachineycodeIn(List<String> values) {
            addCriterion("FARMMACHINEYCODE in", values, "farmmachineycode");
            return (Criteria) this;
        }

        public Criteria andFarmmachineycodeNotIn(List<String> values) {
            addCriterion("FARMMACHINEYCODE not in", values, "farmmachineycode");
            return (Criteria) this;
        }

        public Criteria andFarmmachineycodeBetween(String value1, String value2) {
            addCriterion("FARMMACHINEYCODE between", value1, value2, "farmmachineycode");
            return (Criteria) this;
        }

        public Criteria andFarmmachineycodeNotBetween(String value1, String value2) {
            addCriterion("FARMMACHINEYCODE not between", value1, value2, "farmmachineycode");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcIsNull() {
            addCriterion("CREATEDONUTC is null");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcIsNotNull() {
            addCriterion("CREATEDONUTC is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDONUTC =", value, "createdonutc");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcNotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDONUTC <>", value, "createdonutc");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATEDONUTC >", value, "createdonutc");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDONUTC >=", value, "createdonutc");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcLessThan(Date value) {
            addCriterionForJDBCDate("CREATEDONUTC <", value, "createdonutc");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDONUTC <=", value, "createdonutc");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcIn(List<Date> values) {
            addCriterionForJDBCDate("CREATEDONUTC in", values, "createdonutc");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcNotIn(List<Date> values) {
            addCriterionForJDBCDate("CREATEDONUTC not in", values, "createdonutc");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATEDONUTC between", value1, value2, "createdonutc");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATEDONUTC not between", value1, value2, "createdonutc");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andIsauditIsNull() {
            addCriterion("ISAUDIT is null");
            return (Criteria) this;
        }

        public Criteria andIsauditIsNotNull() {
            addCriterion("ISAUDIT is not null");
            return (Criteria) this;
        }

        public Criteria andIsauditEqualTo(String value) {
            addCriterion("ISAUDIT =", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditNotEqualTo(String value) {
            addCriterion("ISAUDIT <>", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditGreaterThan(String value) {
            addCriterion("ISAUDIT >", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditGreaterThanOrEqualTo(String value) {
            addCriterion("ISAUDIT >=", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditLessThan(String value) {
            addCriterion("ISAUDIT <", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditLessThanOrEqualTo(String value) {
            addCriterion("ISAUDIT <=", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditLike(String value) {
            addCriterion("ISAUDIT like", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditNotLike(String value) {
            addCriterion("ISAUDIT not like", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditIn(List<String> values) {
            addCriterion("ISAUDIT in", values, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditNotIn(List<String> values) {
            addCriterion("ISAUDIT not in", values, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditBetween(String value1, String value2) {
            addCriterion("ISAUDIT between", value1, value2, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditNotBetween(String value1, String value2) {
            addCriterion("ISAUDIT not between", value1, value2, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIsNull() {
            addCriterion("ISDELETED is null");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIsNotNull() {
            addCriterion("ISDELETED is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeletedEqualTo(String value) {
            addCriterion("ISDELETED =", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotEqualTo(String value) {
            addCriterion("ISDELETED <>", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedGreaterThan(String value) {
            addCriterion("ISDELETED >", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedGreaterThanOrEqualTo(String value) {
            addCriterion("ISDELETED >=", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLessThan(String value) {
            addCriterion("ISDELETED <", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLessThanOrEqualTo(String value) {
            addCriterion("ISDELETED <=", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLike(String value) {
            addCriterion("ISDELETED like", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotLike(String value) {
            addCriterion("ISDELETED not like", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIn(List<String> values) {
            addCriterion("ISDELETED in", values, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotIn(List<String> values) {
            addCriterion("ISDELETED not in", values, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedBetween(String value1, String value2) {
            addCriterion("ISDELETED between", value1, value2, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotBetween(String value1, String value2) {
            addCriterion("ISDELETED not between", value1, value2, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("MODIFIER is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("MODIFIER is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("MODIFIER =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("MODIFIER <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("MODIFIER >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFIER >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("MODIFIER <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("MODIFIER <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("MODIFIER like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("MODIFIER not like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("MODIFIER in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("MODIFIER not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("MODIFIER between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("MODIFIER not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcIsNull() {
            addCriterion("UPDATEDONUTC is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcIsNotNull() {
            addCriterion("UPDATEDONUTC is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATEDONUTC =", value, "updatedonutc");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcNotEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATEDONUTC <>", value, "updatedonutc");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcGreaterThan(Date value) {
            addCriterionForJDBCDate("UPDATEDONUTC >", value, "updatedonutc");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATEDONUTC >=", value, "updatedonutc");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcLessThan(Date value) {
            addCriterionForJDBCDate("UPDATEDONUTC <", value, "updatedonutc");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATEDONUTC <=", value, "updatedonutc");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATEDONUTC in", values, "updatedonutc");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcNotIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATEDONUTC not in", values, "updatedonutc");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATEDONUTC between", value1, value2, "updatedonutc");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATEDONUTC not between", value1, value2, "updatedonutc");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeIsNull() {
            addCriterion("CREATORDEPTCODE is null");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeIsNotNull() {
            addCriterion("CREATORDEPTCODE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeEqualTo(String value) {
            addCriterion("CREATORDEPTCODE =", value, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeNotEqualTo(String value) {
            addCriterion("CREATORDEPTCODE <>", value, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeGreaterThan(String value) {
            addCriterion("CREATORDEPTCODE >", value, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATORDEPTCODE >=", value, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeLessThan(String value) {
            addCriterion("CREATORDEPTCODE <", value, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeLessThanOrEqualTo(String value) {
            addCriterion("CREATORDEPTCODE <=", value, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeLike(String value) {
            addCriterion("CREATORDEPTCODE like", value, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeNotLike(String value) {
            addCriterion("CREATORDEPTCODE not like", value, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeIn(List<String> values) {
            addCriterion("CREATORDEPTCODE in", values, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeNotIn(List<String> values) {
            addCriterion("CREATORDEPTCODE not in", values, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeBetween(String value1, String value2) {
            addCriterion("CREATORDEPTCODE between", value1, value2, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeNotBetween(String value1, String value2) {
            addCriterion("CREATORDEPTCODE not between", value1, value2, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("TYPE =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("TYPE <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("TYPE >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("TYPE <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("TYPE <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("TYPE like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("TYPE not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("TYPE in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("TYPE not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andEnterprisecreditcodeIsNull() {
            addCriterion("ENTERPRISECREDITCODE is null");
            return (Criteria) this;
        }

        public Criteria andEnterprisecreditcodeIsNotNull() {
            addCriterion("ENTERPRISECREDITCODE is not null");
            return (Criteria) this;
        }

        public Criteria andEnterprisecreditcodeEqualTo(String value) {
            addCriterion("ENTERPRISECREDITCODE =", value, "enterprisecreditcode");
            return (Criteria) this;
        }

        public Criteria andEnterprisecreditcodeNotEqualTo(String value) {
            addCriterion("ENTERPRISECREDITCODE <>", value, "enterprisecreditcode");
            return (Criteria) this;
        }

        public Criteria andEnterprisecreditcodeGreaterThan(String value) {
            addCriterion("ENTERPRISECREDITCODE >", value, "enterprisecreditcode");
            return (Criteria) this;
        }

        public Criteria andEnterprisecreditcodeGreaterThanOrEqualTo(String value) {
            addCriterion("ENTERPRISECREDITCODE >=", value, "enterprisecreditcode");
            return (Criteria) this;
        }

        public Criteria andEnterprisecreditcodeLessThan(String value) {
            addCriterion("ENTERPRISECREDITCODE <", value, "enterprisecreditcode");
            return (Criteria) this;
        }

        public Criteria andEnterprisecreditcodeLessThanOrEqualTo(String value) {
            addCriterion("ENTERPRISECREDITCODE <=", value, "enterprisecreditcode");
            return (Criteria) this;
        }

        public Criteria andEnterprisecreditcodeLike(String value) {
            addCriterion("ENTERPRISECREDITCODE like", value, "enterprisecreditcode");
            return (Criteria) this;
        }

        public Criteria andEnterprisecreditcodeNotLike(String value) {
            addCriterion("ENTERPRISECREDITCODE not like", value, "enterprisecreditcode");
            return (Criteria) this;
        }

        public Criteria andEnterprisecreditcodeIn(List<String> values) {
            addCriterion("ENTERPRISECREDITCODE in", values, "enterprisecreditcode");
            return (Criteria) this;
        }

        public Criteria andEnterprisecreditcodeNotIn(List<String> values) {
            addCriterion("ENTERPRISECREDITCODE not in", values, "enterprisecreditcode");
            return (Criteria) this;
        }

        public Criteria andEnterprisecreditcodeBetween(String value1, String value2) {
            addCriterion("ENTERPRISECREDITCODE between", value1, value2, "enterprisecreditcode");
            return (Criteria) this;
        }

        public Criteria andEnterprisecreditcodeNotBetween(String value1, String value2) {
            addCriterion("ENTERPRISECREDITCODE not between", value1, value2, "enterprisecreditcode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ZLNF_FARMMACHINEYUSER
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 18 15:49:26 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ZLNF_FARMMACHINEYUSER
     *
     * @mbggenerated Tue Jul 18 15:49:26 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}