package com.vt.fencing.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ZlnfStorageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZLNF_STORAGE
     *
     * @mbggenerated Tue Sep 26 16:54:24 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZLNF_STORAGE
     *
     * @mbggenerated Tue Sep 26 16:54:24 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZLNF_STORAGE
     *
     * @mbggenerated Tue Sep 26 16:54:24 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_STORAGE
     *
     * @mbggenerated Tue Sep 26 16:54:24 CST 2017
     */
    public ZlnfStorageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_STORAGE
     *
     * @mbggenerated Tue Sep 26 16:54:24 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_STORAGE
     *
     * @mbggenerated Tue Sep 26 16:54:24 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_STORAGE
     *
     * @mbggenerated Tue Sep 26 16:54:24 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_STORAGE
     *
     * @mbggenerated Tue Sep 26 16:54:24 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_STORAGE
     *
     * @mbggenerated Tue Sep 26 16:54:24 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_STORAGE
     *
     * @mbggenerated Tue Sep 26 16:54:24 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_STORAGE
     *
     * @mbggenerated Tue Sep 26 16:54:24 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_STORAGE
     *
     * @mbggenerated Tue Sep 26 16:54:24 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_STORAGE
     *
     * @mbggenerated Tue Sep 26 16:54:24 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_STORAGE
     *
     * @mbggenerated Tue Sep 26 16:54:24 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ZLNF_STORAGE
     *
     * @mbggenerated Tue Sep 26 16:54:24 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRkidIsNull() {
            addCriterion("RKID is null");
            return (Criteria) this;
        }

        public Criteria andRkidIsNotNull() {
            addCriterion("RKID is not null");
            return (Criteria) this;
        }

        public Criteria andRkidEqualTo(String value) {
            addCriterion("RKID =", value, "rkid");
            return (Criteria) this;
        }

        public Criteria andRkidNotEqualTo(String value) {
            addCriterion("RKID <>", value, "rkid");
            return (Criteria) this;
        }

        public Criteria andRkidGreaterThan(String value) {
            addCriterion("RKID >", value, "rkid");
            return (Criteria) this;
        }

        public Criteria andRkidGreaterThanOrEqualTo(String value) {
            addCriterion("RKID >=", value, "rkid");
            return (Criteria) this;
        }

        public Criteria andRkidLessThan(String value) {
            addCriterion("RKID <", value, "rkid");
            return (Criteria) this;
        }

        public Criteria andRkidLessThanOrEqualTo(String value) {
            addCriterion("RKID <=", value, "rkid");
            return (Criteria) this;
        }

        public Criteria andRkidLike(String value) {
            addCriterion("RKID like", value, "rkid");
            return (Criteria) this;
        }

        public Criteria andRkidNotLike(String value) {
            addCriterion("RKID not like", value, "rkid");
            return (Criteria) this;
        }

        public Criteria andRkidIn(List<String> values) {
            addCriterion("RKID in", values, "rkid");
            return (Criteria) this;
        }

        public Criteria andRkidNotIn(List<String> values) {
            addCriterion("RKID not in", values, "rkid");
            return (Criteria) this;
        }

        public Criteria andRkidBetween(String value1, String value2) {
            addCriterion("RKID between", value1, value2, "rkid");
            return (Criteria) this;
        }

        public Criteria andRkidNotBetween(String value1, String value2) {
            addCriterion("RKID not between", value1, value2, "rkid");
            return (Criteria) this;
        }

        public Criteria andHtidIsNull() {
            addCriterion("HTID is null");
            return (Criteria) this;
        }

        public Criteria andHtidIsNotNull() {
            addCriterion("HTID is not null");
            return (Criteria) this;
        }

        public Criteria andHtidEqualTo(String value) {
            addCriterion("HTID =", value, "htid");
            return (Criteria) this;
        }

        public Criteria andHtidNotEqualTo(String value) {
            addCriterion("HTID <>", value, "htid");
            return (Criteria) this;
        }

        public Criteria andHtidGreaterThan(String value) {
            addCriterion("HTID >", value, "htid");
            return (Criteria) this;
        }

        public Criteria andHtidGreaterThanOrEqualTo(String value) {
            addCriterion("HTID >=", value, "htid");
            return (Criteria) this;
        }

        public Criteria andHtidLessThan(String value) {
            addCriterion("HTID <", value, "htid");
            return (Criteria) this;
        }

        public Criteria andHtidLessThanOrEqualTo(String value) {
            addCriterion("HTID <=", value, "htid");
            return (Criteria) this;
        }

        public Criteria andHtidLike(String value) {
            addCriterion("HTID like", value, "htid");
            return (Criteria) this;
        }

        public Criteria andHtidNotLike(String value) {
            addCriterion("HTID not like", value, "htid");
            return (Criteria) this;
        }

        public Criteria andHtidIn(List<String> values) {
            addCriterion("HTID in", values, "htid");
            return (Criteria) this;
        }

        public Criteria andHtidNotIn(List<String> values) {
            addCriterion("HTID not in", values, "htid");
            return (Criteria) this;
        }

        public Criteria andHtidBetween(String value1, String value2) {
            addCriterion("HTID between", value1, value2, "htid");
            return (Criteria) this;
        }

        public Criteria andHtidNotBetween(String value1, String value2) {
            addCriterion("HTID not between", value1, value2, "htid");
            return (Criteria) this;
        }

        public Criteria andXyidIsNull() {
            addCriterion("XYID is null");
            return (Criteria) this;
        }

        public Criteria andXyidIsNotNull() {
            addCriterion("XYID is not null");
            return (Criteria) this;
        }

        public Criteria andXyidEqualTo(String value) {
            addCriterion("XYID =", value, "xyid");
            return (Criteria) this;
        }

        public Criteria andXyidNotEqualTo(String value) {
            addCriterion("XYID <>", value, "xyid");
            return (Criteria) this;
        }

        public Criteria andXyidGreaterThan(String value) {
            addCriterion("XYID >", value, "xyid");
            return (Criteria) this;
        }

        public Criteria andXyidGreaterThanOrEqualTo(String value) {
            addCriterion("XYID >=", value, "xyid");
            return (Criteria) this;
        }

        public Criteria andXyidLessThan(String value) {
            addCriterion("XYID <", value, "xyid");
            return (Criteria) this;
        }

        public Criteria andXyidLessThanOrEqualTo(String value) {
            addCriterion("XYID <=", value, "xyid");
            return (Criteria) this;
        }

        public Criteria andXyidLike(String value) {
            addCriterion("XYID like", value, "xyid");
            return (Criteria) this;
        }

        public Criteria andXyidNotLike(String value) {
            addCriterion("XYID not like", value, "xyid");
            return (Criteria) this;
        }

        public Criteria andXyidIn(List<String> values) {
            addCriterion("XYID in", values, "xyid");
            return (Criteria) this;
        }

        public Criteria andXyidNotIn(List<String> values) {
            addCriterion("XYID not in", values, "xyid");
            return (Criteria) this;
        }

        public Criteria andXyidBetween(String value1, String value2) {
            addCriterion("XYID between", value1, value2, "xyid");
            return (Criteria) this;
        }

        public Criteria andXyidNotBetween(String value1, String value2) {
            addCriterion("XYID not between", value1, value2, "xyid");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterionForJDBCDate("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterionForJDBCDate("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterionForJDBCDate("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andClnameIsNull() {
            addCriterion("CLNAME is null");
            return (Criteria) this;
        }

        public Criteria andClnameIsNotNull() {
            addCriterion("CLNAME is not null");
            return (Criteria) this;
        }

        public Criteria andClnameEqualTo(String value) {
            addCriterion("CLNAME =", value, "clname");
            return (Criteria) this;
        }

        public Criteria andClnameNotEqualTo(String value) {
            addCriterion("CLNAME <>", value, "clname");
            return (Criteria) this;
        }

        public Criteria andClnameGreaterThan(String value) {
            addCriterion("CLNAME >", value, "clname");
            return (Criteria) this;
        }

        public Criteria andClnameGreaterThanOrEqualTo(String value) {
            addCriterion("CLNAME >=", value, "clname");
            return (Criteria) this;
        }

        public Criteria andClnameLessThan(String value) {
            addCriterion("CLNAME <", value, "clname");
            return (Criteria) this;
        }

        public Criteria andClnameLessThanOrEqualTo(String value) {
            addCriterion("CLNAME <=", value, "clname");
            return (Criteria) this;
        }

        public Criteria andClnameLike(String value) {
            addCriterion("CLNAME like", value, "clname");
            return (Criteria) this;
        }

        public Criteria andClnameNotLike(String value) {
            addCriterion("CLNAME not like", value, "clname");
            return (Criteria) this;
        }

        public Criteria andClnameIn(List<String> values) {
            addCriterion("CLNAME in", values, "clname");
            return (Criteria) this;
        }

        public Criteria andClnameNotIn(List<String> values) {
            addCriterion("CLNAME not in", values, "clname");
            return (Criteria) this;
        }

        public Criteria andClnameBetween(String value1, String value2) {
            addCriterion("CLNAME between", value1, value2, "clname");
            return (Criteria) this;
        }

        public Criteria andClnameNotBetween(String value1, String value2) {
            addCriterion("CLNAME not between", value1, value2, "clname");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("USERID is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("USERID is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("USERID =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("USERID <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("USERID >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("USERID >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("USERID <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("USERID <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("USERID like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("USERID not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("USERID in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("USERID not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("USERID between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("USERID not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("PHONE is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("PHONE =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("PHONE <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("PHONE >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("PHONE >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("PHONE <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("PHONE <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("PHONE like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("PHONE not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("PHONE in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("PHONE not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("PHONE between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("PHONE not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andIdnumberIsNull() {
            addCriterion("IDNUMBER is null");
            return (Criteria) this;
        }

        public Criteria andIdnumberIsNotNull() {
            addCriterion("IDNUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andIdnumberEqualTo(String value) {
            addCriterion("IDNUMBER =", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberNotEqualTo(String value) {
            addCriterion("IDNUMBER <>", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberGreaterThan(String value) {
            addCriterion("IDNUMBER >", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberGreaterThanOrEqualTo(String value) {
            addCriterion("IDNUMBER >=", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberLessThan(String value) {
            addCriterion("IDNUMBER <", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberLessThanOrEqualTo(String value) {
            addCriterion("IDNUMBER <=", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberLike(String value) {
            addCriterion("IDNUMBER like", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberNotLike(String value) {
            addCriterion("IDNUMBER not like", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberIn(List<String> values) {
            addCriterion("IDNUMBER in", values, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberNotIn(List<String> values) {
            addCriterion("IDNUMBER not in", values, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberBetween(String value1, String value2) {
            addCriterion("IDNUMBER between", value1, value2, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberNotBetween(String value1, String value2) {
            addCriterion("IDNUMBER not between", value1, value2, "idnumber");
            return (Criteria) this;
        }

        public Criteria andLibnameIsNull() {
            addCriterion("LIBNAME is null");
            return (Criteria) this;
        }

        public Criteria andLibnameIsNotNull() {
            addCriterion("LIBNAME is not null");
            return (Criteria) this;
        }

        public Criteria andLibnameEqualTo(String value) {
            addCriterion("LIBNAME =", value, "libname");
            return (Criteria) this;
        }

        public Criteria andLibnameNotEqualTo(String value) {
            addCriterion("LIBNAME <>", value, "libname");
            return (Criteria) this;
        }

        public Criteria andLibnameGreaterThan(String value) {
            addCriterion("LIBNAME >", value, "libname");
            return (Criteria) this;
        }

        public Criteria andLibnameGreaterThanOrEqualTo(String value) {
            addCriterion("LIBNAME >=", value, "libname");
            return (Criteria) this;
        }

        public Criteria andLibnameLessThan(String value) {
            addCriterion("LIBNAME <", value, "libname");
            return (Criteria) this;
        }

        public Criteria andLibnameLessThanOrEqualTo(String value) {
            addCriterion("LIBNAME <=", value, "libname");
            return (Criteria) this;
        }

        public Criteria andLibnameLike(String value) {
            addCriterion("LIBNAME like", value, "libname");
            return (Criteria) this;
        }

        public Criteria andLibnameNotLike(String value) {
            addCriterion("LIBNAME not like", value, "libname");
            return (Criteria) this;
        }

        public Criteria andLibnameIn(List<String> values) {
            addCriterion("LIBNAME in", values, "libname");
            return (Criteria) this;
        }

        public Criteria andLibnameNotIn(List<String> values) {
            addCriterion("LIBNAME not in", values, "libname");
            return (Criteria) this;
        }

        public Criteria andLibnameBetween(String value1, String value2) {
            addCriterion("LIBNAME between", value1, value2, "libname");
            return (Criteria) this;
        }

        public Criteria andLibnameNotBetween(String value1, String value2) {
            addCriterion("LIBNAME not between", value1, value2, "libname");
            return (Criteria) this;
        }

        public Criteria andLibidIsNull() {
            addCriterion("LIBID is null");
            return (Criteria) this;
        }

        public Criteria andLibidIsNotNull() {
            addCriterion("LIBID is not null");
            return (Criteria) this;
        }

        public Criteria andLibidEqualTo(String value) {
            addCriterion("LIBID =", value, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidNotEqualTo(String value) {
            addCriterion("LIBID <>", value, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidGreaterThan(String value) {
            addCriterion("LIBID >", value, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidGreaterThanOrEqualTo(String value) {
            addCriterion("LIBID >=", value, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidLessThan(String value) {
            addCriterion("LIBID <", value, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidLessThanOrEqualTo(String value) {
            addCriterion("LIBID <=", value, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidLike(String value) {
            addCriterion("LIBID like", value, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidNotLike(String value) {
            addCriterion("LIBID not like", value, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidIn(List<String> values) {
            addCriterion("LIBID in", values, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidNotIn(List<String> values) {
            addCriterion("LIBID not in", values, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidBetween(String value1, String value2) {
            addCriterion("LIBID between", value1, value2, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidNotBetween(String value1, String value2) {
            addCriterion("LIBID not between", value1, value2, "libid");
            return (Criteria) this;
        }

        public Criteria andVarietyIsNull() {
            addCriterion("VARIETY is null");
            return (Criteria) this;
        }

        public Criteria andVarietyIsNotNull() {
            addCriterion("VARIETY is not null");
            return (Criteria) this;
        }

        public Criteria andVarietyEqualTo(String value) {
            addCriterion("VARIETY =", value, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyNotEqualTo(String value) {
            addCriterion("VARIETY <>", value, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyGreaterThan(String value) {
            addCriterion("VARIETY >", value, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyGreaterThanOrEqualTo(String value) {
            addCriterion("VARIETY >=", value, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyLessThan(String value) {
            addCriterion("VARIETY <", value, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyLessThanOrEqualTo(String value) {
            addCriterion("VARIETY <=", value, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyLike(String value) {
            addCriterion("VARIETY like", value, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyNotLike(String value) {
            addCriterion("VARIETY not like", value, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyIn(List<String> values) {
            addCriterion("VARIETY in", values, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyNotIn(List<String> values) {
            addCriterion("VARIETY not in", values, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyBetween(String value1, String value2) {
            addCriterion("VARIETY between", value1, value2, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyNotBetween(String value1, String value2) {
            addCriterion("VARIETY not between", value1, value2, "variety");
            return (Criteria) this;
        }

        public Criteria andHtlevelIsNull() {
            addCriterion("HTLEVEL is null");
            return (Criteria) this;
        }

        public Criteria andHtlevelIsNotNull() {
            addCriterion("HTLEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andHtlevelEqualTo(String value) {
            addCriterion("HTLEVEL =", value, "htlevel");
            return (Criteria) this;
        }

        public Criteria andHtlevelNotEqualTo(String value) {
            addCriterion("HTLEVEL <>", value, "htlevel");
            return (Criteria) this;
        }

        public Criteria andHtlevelGreaterThan(String value) {
            addCriterion("HTLEVEL >", value, "htlevel");
            return (Criteria) this;
        }

        public Criteria andHtlevelGreaterThanOrEqualTo(String value) {
            addCriterion("HTLEVEL >=", value, "htlevel");
            return (Criteria) this;
        }

        public Criteria andHtlevelLessThan(String value) {
            addCriterion("HTLEVEL <", value, "htlevel");
            return (Criteria) this;
        }

        public Criteria andHtlevelLessThanOrEqualTo(String value) {
            addCriterion("HTLEVEL <=", value, "htlevel");
            return (Criteria) this;
        }

        public Criteria andHtlevelLike(String value) {
            addCriterion("HTLEVEL like", value, "htlevel");
            return (Criteria) this;
        }

        public Criteria andHtlevelNotLike(String value) {
            addCriterion("HTLEVEL not like", value, "htlevel");
            return (Criteria) this;
        }

        public Criteria andHtlevelIn(List<String> values) {
            addCriterion("HTLEVEL in", values, "htlevel");
            return (Criteria) this;
        }

        public Criteria andHtlevelNotIn(List<String> values) {
            addCriterion("HTLEVEL not in", values, "htlevel");
            return (Criteria) this;
        }

        public Criteria andHtlevelBetween(String value1, String value2) {
            addCriterion("HTLEVEL between", value1, value2, "htlevel");
            return (Criteria) this;
        }

        public Criteria andHtlevelNotBetween(String value1, String value2) {
            addCriterion("HTLEVEL not between", value1, value2, "htlevel");
            return (Criteria) this;
        }

        public Criteria andGlshuifenIsNull() {
            addCriterion("GLSHUIFEN is null");
            return (Criteria) this;
        }

        public Criteria andGlshuifenIsNotNull() {
            addCriterion("GLSHUIFEN is not null");
            return (Criteria) this;
        }

        public Criteria andGlshuifenEqualTo(String value) {
            addCriterion("GLSHUIFEN =", value, "glshuifen");
            return (Criteria) this;
        }

        public Criteria andGlshuifenNotEqualTo(String value) {
            addCriterion("GLSHUIFEN <>", value, "glshuifen");
            return (Criteria) this;
        }

        public Criteria andGlshuifenGreaterThan(String value) {
            addCriterion("GLSHUIFEN >", value, "glshuifen");
            return (Criteria) this;
        }

        public Criteria andGlshuifenGreaterThanOrEqualTo(String value) {
            addCriterion("GLSHUIFEN >=", value, "glshuifen");
            return (Criteria) this;
        }

        public Criteria andGlshuifenLessThan(String value) {
            addCriterion("GLSHUIFEN <", value, "glshuifen");
            return (Criteria) this;
        }

        public Criteria andGlshuifenLessThanOrEqualTo(String value) {
            addCriterion("GLSHUIFEN <=", value, "glshuifen");
            return (Criteria) this;
        }

        public Criteria andGlshuifenLike(String value) {
            addCriterion("GLSHUIFEN like", value, "glshuifen");
            return (Criteria) this;
        }

        public Criteria andGlshuifenNotLike(String value) {
            addCriterion("GLSHUIFEN not like", value, "glshuifen");
            return (Criteria) this;
        }

        public Criteria andGlshuifenIn(List<String> values) {
            addCriterion("GLSHUIFEN in", values, "glshuifen");
            return (Criteria) this;
        }

        public Criteria andGlshuifenNotIn(List<String> values) {
            addCriterion("GLSHUIFEN not in", values, "glshuifen");
            return (Criteria) this;
        }

        public Criteria andGlshuifenBetween(String value1, String value2) {
            addCriterion("GLSHUIFEN between", value1, value2, "glshuifen");
            return (Criteria) this;
        }

        public Criteria andGlshuifenNotBetween(String value1, String value2) {
            addCriterion("GLSHUIFEN not between", value1, value2, "glshuifen");
            return (Criteria) this;
        }

        public Criteria andCntIsNull() {
            addCriterion("CNT is null");
            return (Criteria) this;
        }

        public Criteria andCntIsNotNull() {
            addCriterion("CNT is not null");
            return (Criteria) this;
        }

        public Criteria andCntEqualTo(String value) {
            addCriterion("CNT =", value, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntNotEqualTo(String value) {
            addCriterion("CNT <>", value, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntGreaterThan(String value) {
            addCriterion("CNT >", value, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntGreaterThanOrEqualTo(String value) {
            addCriterion("CNT >=", value, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntLessThan(String value) {
            addCriterion("CNT <", value, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntLessThanOrEqualTo(String value) {
            addCriterion("CNT <=", value, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntLike(String value) {
            addCriterion("CNT like", value, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntNotLike(String value) {
            addCriterion("CNT not like", value, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntIn(List<String> values) {
            addCriterion("CNT in", values, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntNotIn(List<String> values) {
            addCriterion("CNT not in", values, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntBetween(String value1, String value2) {
            addCriterion("CNT between", value1, value2, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntNotBetween(String value1, String value2) {
            addCriterion("CNT not between", value1, value2, "cnt");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("PRICE is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(String value) {
            addCriterion("PRICE =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(String value) {
            addCriterion("PRICE <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(String value) {
            addCriterion("PRICE >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(String value) {
            addCriterion("PRICE >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(String value) {
            addCriterion("PRICE <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(String value) {
            addCriterion("PRICE <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLike(String value) {
            addCriterion("PRICE like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotLike(String value) {
            addCriterion("PRICE not like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<String> values) {
            addCriterion("PRICE in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<String> values) {
            addCriterion("PRICE not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(String value1, String value2) {
            addCriterion("PRICE between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(String value1, String value2) {
            addCriterion("PRICE not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andActionstateIsNull() {
            addCriterion("ACTIONSTATE is null");
            return (Criteria) this;
        }

        public Criteria andActionstateIsNotNull() {
            addCriterion("ACTIONSTATE is not null");
            return (Criteria) this;
        }

        public Criteria andActionstateEqualTo(String value) {
            addCriterion("ACTIONSTATE =", value, "actionstate");
            return (Criteria) this;
        }

        public Criteria andActionstateNotEqualTo(String value) {
            addCriterion("ACTIONSTATE <>", value, "actionstate");
            return (Criteria) this;
        }

        public Criteria andActionstateGreaterThan(String value) {
            addCriterion("ACTIONSTATE >", value, "actionstate");
            return (Criteria) this;
        }

        public Criteria andActionstateGreaterThanOrEqualTo(String value) {
            addCriterion("ACTIONSTATE >=", value, "actionstate");
            return (Criteria) this;
        }

        public Criteria andActionstateLessThan(String value) {
            addCriterion("ACTIONSTATE <", value, "actionstate");
            return (Criteria) this;
        }

        public Criteria andActionstateLessThanOrEqualTo(String value) {
            addCriterion("ACTIONSTATE <=", value, "actionstate");
            return (Criteria) this;
        }

        public Criteria andActionstateLike(String value) {
            addCriterion("ACTIONSTATE like", value, "actionstate");
            return (Criteria) this;
        }

        public Criteria andActionstateNotLike(String value) {
            addCriterion("ACTIONSTATE not like", value, "actionstate");
            return (Criteria) this;
        }

        public Criteria andActionstateIn(List<String> values) {
            addCriterion("ACTIONSTATE in", values, "actionstate");
            return (Criteria) this;
        }

        public Criteria andActionstateNotIn(List<String> values) {
            addCriterion("ACTIONSTATE not in", values, "actionstate");
            return (Criteria) this;
        }

        public Criteria andActionstateBetween(String value1, String value2) {
            addCriterion("ACTIONSTATE between", value1, value2, "actionstate");
            return (Criteria) this;
        }

        public Criteria andActionstateNotBetween(String value1, String value2) {
            addCriterion("ACTIONSTATE not between", value1, value2, "actionstate");
            return (Criteria) this;
        }

        public Criteria andReturnstateIsNull() {
            addCriterion("RETURNSTATE is null");
            return (Criteria) this;
        }

        public Criteria andReturnstateIsNotNull() {
            addCriterion("RETURNSTATE is not null");
            return (Criteria) this;
        }

        public Criteria andReturnstateEqualTo(String value) {
            addCriterion("RETURNSTATE =", value, "returnstate");
            return (Criteria) this;
        }

        public Criteria andReturnstateNotEqualTo(String value) {
            addCriterion("RETURNSTATE <>", value, "returnstate");
            return (Criteria) this;
        }

        public Criteria andReturnstateGreaterThan(String value) {
            addCriterion("RETURNSTATE >", value, "returnstate");
            return (Criteria) this;
        }

        public Criteria andReturnstateGreaterThanOrEqualTo(String value) {
            addCriterion("RETURNSTATE >=", value, "returnstate");
            return (Criteria) this;
        }

        public Criteria andReturnstateLessThan(String value) {
            addCriterion("RETURNSTATE <", value, "returnstate");
            return (Criteria) this;
        }

        public Criteria andReturnstateLessThanOrEqualTo(String value) {
            addCriterion("RETURNSTATE <=", value, "returnstate");
            return (Criteria) this;
        }

        public Criteria andReturnstateLike(String value) {
            addCriterion("RETURNSTATE like", value, "returnstate");
            return (Criteria) this;
        }

        public Criteria andReturnstateNotLike(String value) {
            addCriterion("RETURNSTATE not like", value, "returnstate");
            return (Criteria) this;
        }

        public Criteria andReturnstateIn(List<String> values) {
            addCriterion("RETURNSTATE in", values, "returnstate");
            return (Criteria) this;
        }

        public Criteria andReturnstateNotIn(List<String> values) {
            addCriterion("RETURNSTATE not in", values, "returnstate");
            return (Criteria) this;
        }

        public Criteria andReturnstateBetween(String value1, String value2) {
            addCriterion("RETURNSTATE between", value1, value2, "returnstate");
            return (Criteria) this;
        }

        public Criteria andReturnstateNotBetween(String value1, String value2) {
            addCriterion("RETURNSTATE not between", value1, value2, "returnstate");
            return (Criteria) this;
        }

        public Criteria andSettlementstateIsNull() {
            addCriterion("SETTLEMENTSTATE is null");
            return (Criteria) this;
        }

        public Criteria andSettlementstateIsNotNull() {
            addCriterion("SETTLEMENTSTATE is not null");
            return (Criteria) this;
        }

        public Criteria andSettlementstateEqualTo(String value) {
            addCriterion("SETTLEMENTSTATE =", value, "settlementstate");
            return (Criteria) this;
        }

        public Criteria andSettlementstateNotEqualTo(String value) {
            addCriterion("SETTLEMENTSTATE <>", value, "settlementstate");
            return (Criteria) this;
        }

        public Criteria andSettlementstateGreaterThan(String value) {
            addCriterion("SETTLEMENTSTATE >", value, "settlementstate");
            return (Criteria) this;
        }

        public Criteria andSettlementstateGreaterThanOrEqualTo(String value) {
            addCriterion("SETTLEMENTSTATE >=", value, "settlementstate");
            return (Criteria) this;
        }

        public Criteria andSettlementstateLessThan(String value) {
            addCriterion("SETTLEMENTSTATE <", value, "settlementstate");
            return (Criteria) this;
        }

        public Criteria andSettlementstateLessThanOrEqualTo(String value) {
            addCriterion("SETTLEMENTSTATE <=", value, "settlementstate");
            return (Criteria) this;
        }

        public Criteria andSettlementstateLike(String value) {
            addCriterion("SETTLEMENTSTATE like", value, "settlementstate");
            return (Criteria) this;
        }

        public Criteria andSettlementstateNotLike(String value) {
            addCriterion("SETTLEMENTSTATE not like", value, "settlementstate");
            return (Criteria) this;
        }

        public Criteria andSettlementstateIn(List<String> values) {
            addCriterion("SETTLEMENTSTATE in", values, "settlementstate");
            return (Criteria) this;
        }

        public Criteria andSettlementstateNotIn(List<String> values) {
            addCriterion("SETTLEMENTSTATE not in", values, "settlementstate");
            return (Criteria) this;
        }

        public Criteria andSettlementstateBetween(String value1, String value2) {
            addCriterion("SETTLEMENTSTATE between", value1, value2, "settlementstate");
            return (Criteria) this;
        }

        public Criteria andSettlementstateNotBetween(String value1, String value2) {
            addCriterion("SETTLEMENTSTATE not between", value1, value2, "settlementstate");
            return (Criteria) this;
        }

        public Criteria andVarietycodeIsNull() {
            addCriterion("VARIETYCODE is null");
            return (Criteria) this;
        }

        public Criteria andVarietycodeIsNotNull() {
            addCriterion("VARIETYCODE is not null");
            return (Criteria) this;
        }

        public Criteria andVarietycodeEqualTo(String value) {
            addCriterion("VARIETYCODE =", value, "varietycode");
            return (Criteria) this;
        }

        public Criteria andVarietycodeNotEqualTo(String value) {
            addCriterion("VARIETYCODE <>", value, "varietycode");
            return (Criteria) this;
        }

        public Criteria andVarietycodeGreaterThan(String value) {
            addCriterion("VARIETYCODE >", value, "varietycode");
            return (Criteria) this;
        }

        public Criteria andVarietycodeGreaterThanOrEqualTo(String value) {
            addCriterion("VARIETYCODE >=", value, "varietycode");
            return (Criteria) this;
        }

        public Criteria andVarietycodeLessThan(String value) {
            addCriterion("VARIETYCODE <", value, "varietycode");
            return (Criteria) this;
        }

        public Criteria andVarietycodeLessThanOrEqualTo(String value) {
            addCriterion("VARIETYCODE <=", value, "varietycode");
            return (Criteria) this;
        }

        public Criteria andVarietycodeLike(String value) {
            addCriterion("VARIETYCODE like", value, "varietycode");
            return (Criteria) this;
        }

        public Criteria andVarietycodeNotLike(String value) {
            addCriterion("VARIETYCODE not like", value, "varietycode");
            return (Criteria) this;
        }

        public Criteria andVarietycodeIn(List<String> values) {
            addCriterion("VARIETYCODE in", values, "varietycode");
            return (Criteria) this;
        }

        public Criteria andVarietycodeNotIn(List<String> values) {
            addCriterion("VARIETYCODE not in", values, "varietycode");
            return (Criteria) this;
        }

        public Criteria andVarietycodeBetween(String value1, String value2) {
            addCriterion("VARIETYCODE between", value1, value2, "varietycode");
            return (Criteria) this;
        }

        public Criteria andVarietycodeNotBetween(String value1, String value2) {
            addCriterion("VARIETYCODE not between", value1, value2, "varietycode");
            return (Criteria) this;
        }

        public Criteria andHtlevelcodeIsNull() {
            addCriterion("HTLEVELCODE is null");
            return (Criteria) this;
        }

        public Criteria andHtlevelcodeIsNotNull() {
            addCriterion("HTLEVELCODE is not null");
            return (Criteria) this;
        }

        public Criteria andHtlevelcodeEqualTo(String value) {
            addCriterion("HTLEVELCODE =", value, "htlevelcode");
            return (Criteria) this;
        }

        public Criteria andHtlevelcodeNotEqualTo(String value) {
            addCriterion("HTLEVELCODE <>", value, "htlevelcode");
            return (Criteria) this;
        }

        public Criteria andHtlevelcodeGreaterThan(String value) {
            addCriterion("HTLEVELCODE >", value, "htlevelcode");
            return (Criteria) this;
        }

        public Criteria andHtlevelcodeGreaterThanOrEqualTo(String value) {
            addCriterion("HTLEVELCODE >=", value, "htlevelcode");
            return (Criteria) this;
        }

        public Criteria andHtlevelcodeLessThan(String value) {
            addCriterion("HTLEVELCODE <", value, "htlevelcode");
            return (Criteria) this;
        }

        public Criteria andHtlevelcodeLessThanOrEqualTo(String value) {
            addCriterion("HTLEVELCODE <=", value, "htlevelcode");
            return (Criteria) this;
        }

        public Criteria andHtlevelcodeLike(String value) {
            addCriterion("HTLEVELCODE like", value, "htlevelcode");
            return (Criteria) this;
        }

        public Criteria andHtlevelcodeNotLike(String value) {
            addCriterion("HTLEVELCODE not like", value, "htlevelcode");
            return (Criteria) this;
        }

        public Criteria andHtlevelcodeIn(List<String> values) {
            addCriterion("HTLEVELCODE in", values, "htlevelcode");
            return (Criteria) this;
        }

        public Criteria andHtlevelcodeNotIn(List<String> values) {
            addCriterion("HTLEVELCODE not in", values, "htlevelcode");
            return (Criteria) this;
        }

        public Criteria andHtlevelcodeBetween(String value1, String value2) {
            addCriterion("HTLEVELCODE between", value1, value2, "htlevelcode");
            return (Criteria) this;
        }

        public Criteria andHtlevelcodeNotBetween(String value1, String value2) {
            addCriterion("HTLEVELCODE not between", value1, value2, "htlevelcode");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("ISDELETE is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("ISDELETE is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(String value) {
            addCriterion("ISDELETE =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(String value) {
            addCriterion("ISDELETE <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(String value) {
            addCriterion("ISDELETE >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(String value) {
            addCriterion("ISDELETE >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(String value) {
            addCriterion("ISDELETE <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(String value) {
            addCriterion("ISDELETE <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLike(String value) {
            addCriterion("ISDELETE like", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotLike(String value) {
            addCriterion("ISDELETE not like", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<String> values) {
            addCriterion("ISDELETE in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<String> values) {
            addCriterion("ISDELETE not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(String value1, String value2) {
            addCriterion("ISDELETE between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(String value1, String value2) {
            addCriterion("ISDELETE not between", value1, value2, "isdelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ZLNF_STORAGE
     *
     * @mbggenerated do_not_delete_during_merge Tue Sep 26 16:54:24 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ZLNF_STORAGE
     *
     * @mbggenerated Tue Sep 26 16:54:24 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}