package com.vt.fencing.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ZlnfServiceProgramExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZLNF_SERVICEPROGRAM
     *
     * @mbggenerated Fri Aug 18 11:52:30 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZLNF_SERVICEPROGRAM
     *
     * @mbggenerated Fri Aug 18 11:52:30 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZLNF_SERVICEPROGRAM
     *
     * @mbggenerated Fri Aug 18 11:52:30 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_SERVICEPROGRAM
     *
     * @mbggenerated Fri Aug 18 11:52:30 CST 2017
     */
    public ZlnfServiceProgramExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_SERVICEPROGRAM
     *
     * @mbggenerated Fri Aug 18 11:52:30 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_SERVICEPROGRAM
     *
     * @mbggenerated Fri Aug 18 11:52:30 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_SERVICEPROGRAM
     *
     * @mbggenerated Fri Aug 18 11:52:30 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_SERVICEPROGRAM
     *
     * @mbggenerated Fri Aug 18 11:52:30 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_SERVICEPROGRAM
     *
     * @mbggenerated Fri Aug 18 11:52:30 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_SERVICEPROGRAM
     *
     * @mbggenerated Fri Aug 18 11:52:30 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_SERVICEPROGRAM
     *
     * @mbggenerated Fri Aug 18 11:52:30 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_SERVICEPROGRAM
     *
     * @mbggenerated Fri Aug 18 11:52:30 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_SERVICEPROGRAM
     *
     * @mbggenerated Fri Aug 18 11:52:30 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_SERVICEPROGRAM
     *
     * @mbggenerated Fri Aug 18 11:52:30 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ZLNF_SERVICEPROGRAM
     *
     * @mbggenerated Fri Aug 18 11:52:30 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andServicecodeIsNull() {
            addCriterion("SERVICECODE is null");
            return (Criteria) this;
        }

        public Criteria andServicecodeIsNotNull() {
            addCriterion("SERVICECODE is not null");
            return (Criteria) this;
        }

        public Criteria andServicecodeEqualTo(String value) {
            addCriterion("SERVICECODE =", value, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeNotEqualTo(String value) {
            addCriterion("SERVICECODE <>", value, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeGreaterThan(String value) {
            addCriterion("SERVICECODE >", value, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeGreaterThanOrEqualTo(String value) {
            addCriterion("SERVICECODE >=", value, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeLessThan(String value) {
            addCriterion("SERVICECODE <", value, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeLessThanOrEqualTo(String value) {
            addCriterion("SERVICECODE <=", value, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeLike(String value) {
            addCriterion("SERVICECODE like", value, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeNotLike(String value) {
            addCriterion("SERVICECODE not like", value, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeIn(List<String> values) {
            addCriterion("SERVICECODE in", values, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeNotIn(List<String> values) {
            addCriterion("SERVICECODE not in", values, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeBetween(String value1, String value2) {
            addCriterion("SERVICECODE between", value1, value2, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeNotBetween(String value1, String value2) {
            addCriterion("SERVICECODE not between", value1, value2, "servicecode");
            return (Criteria) this;
        }

        public Criteria andFoodkindIsNull() {
            addCriterion("FOODKIND is null");
            return (Criteria) this;
        }

        public Criteria andFoodkindIsNotNull() {
            addCriterion("FOODKIND is not null");
            return (Criteria) this;
        }

        public Criteria andFoodkindEqualTo(String value) {
            addCriterion("FOODKIND =", value, "foodkind");
            return (Criteria) this;
        }

        public Criteria andFoodkindNotEqualTo(String value) {
            addCriterion("FOODKIND <>", value, "foodkind");
            return (Criteria) this;
        }

        public Criteria andFoodkindGreaterThan(String value) {
            addCriterion("FOODKIND >", value, "foodkind");
            return (Criteria) this;
        }

        public Criteria andFoodkindGreaterThanOrEqualTo(String value) {
            addCriterion("FOODKIND >=", value, "foodkind");
            return (Criteria) this;
        }

        public Criteria andFoodkindLessThan(String value) {
            addCriterion("FOODKIND <", value, "foodkind");
            return (Criteria) this;
        }

        public Criteria andFoodkindLessThanOrEqualTo(String value) {
            addCriterion("FOODKIND <=", value, "foodkind");
            return (Criteria) this;
        }

        public Criteria andFoodkindLike(String value) {
            addCriterion("FOODKIND like", value, "foodkind");
            return (Criteria) this;
        }

        public Criteria andFoodkindNotLike(String value) {
            addCriterion("FOODKIND not like", value, "foodkind");
            return (Criteria) this;
        }

        public Criteria andFoodkindIn(List<String> values) {
            addCriterion("FOODKIND in", values, "foodkind");
            return (Criteria) this;
        }

        public Criteria andFoodkindNotIn(List<String> values) {
            addCriterion("FOODKIND not in", values, "foodkind");
            return (Criteria) this;
        }

        public Criteria andFoodkindBetween(String value1, String value2) {
            addCriterion("FOODKIND between", value1, value2, "foodkind");
            return (Criteria) this;
        }

        public Criteria andFoodkindNotBetween(String value1, String value2) {
            addCriterion("FOODKIND not between", value1, value2, "foodkind");
            return (Criteria) this;
        }

        public Criteria andServicepriceIsNull() {
            addCriterion("SERVICEPRICE is null");
            return (Criteria) this;
        }

        public Criteria andServicepriceIsNotNull() {
            addCriterion("SERVICEPRICE is not null");
            return (Criteria) this;
        }

        public Criteria andServicepriceEqualTo(Double value) {
            addCriterion("SERVICEPRICE =", value, "serviceprice");
            return (Criteria) this;
        }

        public Criteria andServicepriceNotEqualTo(Double value) {
            addCriterion("SERVICEPRICE <>", value, "serviceprice");
            return (Criteria) this;
        }

        public Criteria andServicepriceGreaterThan(Double value) {
            addCriterion("SERVICEPRICE >", value, "serviceprice");
            return (Criteria) this;
        }

        public Criteria andServicepriceGreaterThanOrEqualTo(Double value) {
            addCriterion("SERVICEPRICE >=", value, "serviceprice");
            return (Criteria) this;
        }

        public Criteria andServicepriceLessThan(Double value) {
            addCriterion("SERVICEPRICE <", value, "serviceprice");
            return (Criteria) this;
        }

        public Criteria andServicepriceLessThanOrEqualTo(Double value) {
            addCriterion("SERVICEPRICE <=", value, "serviceprice");
            return (Criteria) this;
        }

        public Criteria andServicepriceIn(List<Double> values) {
            addCriterion("SERVICEPRICE in", values, "serviceprice");
            return (Criteria) this;
        }

        public Criteria andServicepriceNotIn(List<Double> values) {
            addCriterion("SERVICEPRICE not in", values, "serviceprice");
            return (Criteria) this;
        }

        public Criteria andServicepriceBetween(Double value1, Double value2) {
            addCriterion("SERVICEPRICE between", value1, value2, "serviceprice");
            return (Criteria) this;
        }

        public Criteria andServicepriceNotBetween(Double value1, Double value2) {
            addCriterion("SERVICEPRICE not between", value1, value2, "serviceprice");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcIsNull() {
            addCriterion("CREATEDONUTC is null");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcIsNotNull() {
            addCriterion("CREATEDONUTC is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDONUTC =", value, "createdonutc");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcNotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDONUTC <>", value, "createdonutc");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATEDONUTC >", value, "createdonutc");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDONUTC >=", value, "createdonutc");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcLessThan(Date value) {
            addCriterionForJDBCDate("CREATEDONUTC <", value, "createdonutc");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDONUTC <=", value, "createdonutc");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcIn(List<Date> values) {
            addCriterionForJDBCDate("CREATEDONUTC in", values, "createdonutc");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcNotIn(List<Date> values) {
            addCriterionForJDBCDate("CREATEDONUTC not in", values, "createdonutc");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATEDONUTC between", value1, value2, "createdonutc");
            return (Criteria) this;
        }

        public Criteria andCreatedonutcNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATEDONUTC not between", value1, value2, "createdonutc");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andIsauditIsNull() {
            addCriterion("ISAUDIT is null");
            return (Criteria) this;
        }

        public Criteria andIsauditIsNotNull() {
            addCriterion("ISAUDIT is not null");
            return (Criteria) this;
        }

        public Criteria andIsauditEqualTo(String value) {
            addCriterion("ISAUDIT =", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditNotEqualTo(String value) {
            addCriterion("ISAUDIT <>", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditGreaterThan(String value) {
            addCriterion("ISAUDIT >", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditGreaterThanOrEqualTo(String value) {
            addCriterion("ISAUDIT >=", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditLessThan(String value) {
            addCriterion("ISAUDIT <", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditLessThanOrEqualTo(String value) {
            addCriterion("ISAUDIT <=", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditLike(String value) {
            addCriterion("ISAUDIT like", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditNotLike(String value) {
            addCriterion("ISAUDIT not like", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditIn(List<String> values) {
            addCriterion("ISAUDIT in", values, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditNotIn(List<String> values) {
            addCriterion("ISAUDIT not in", values, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditBetween(String value1, String value2) {
            addCriterion("ISAUDIT between", value1, value2, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditNotBetween(String value1, String value2) {
            addCriterion("ISAUDIT not between", value1, value2, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIsNull() {
            addCriterion("ISDELETED is null");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIsNotNull() {
            addCriterion("ISDELETED is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeletedEqualTo(String value) {
            addCriterion("ISDELETED =", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotEqualTo(String value) {
            addCriterion("ISDELETED <>", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedGreaterThan(String value) {
            addCriterion("ISDELETED >", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedGreaterThanOrEqualTo(String value) {
            addCriterion("ISDELETED >=", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLessThan(String value) {
            addCriterion("ISDELETED <", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLessThanOrEqualTo(String value) {
            addCriterion("ISDELETED <=", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLike(String value) {
            addCriterion("ISDELETED like", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotLike(String value) {
            addCriterion("ISDELETED not like", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIn(List<String> values) {
            addCriterion("ISDELETED in", values, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotIn(List<String> values) {
            addCriterion("ISDELETED not in", values, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedBetween(String value1, String value2) {
            addCriterion("ISDELETED between", value1, value2, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotBetween(String value1, String value2) {
            addCriterion("ISDELETED not between", value1, value2, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("MODIFIER is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("MODIFIER is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("MODIFIER =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("MODIFIER <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("MODIFIER >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFIER >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("MODIFIER <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("MODIFIER <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("MODIFIER like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("MODIFIER not like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("MODIFIER in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("MODIFIER not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("MODIFIER between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("MODIFIER not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcIsNull() {
            addCriterion("UPDATEDONUTC is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcIsNotNull() {
            addCriterion("UPDATEDONUTC is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATEDONUTC =", value, "updatedonutc");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcNotEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATEDONUTC <>", value, "updatedonutc");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcGreaterThan(Date value) {
            addCriterionForJDBCDate("UPDATEDONUTC >", value, "updatedonutc");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATEDONUTC >=", value, "updatedonutc");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcLessThan(Date value) {
            addCriterionForJDBCDate("UPDATEDONUTC <", value, "updatedonutc");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATEDONUTC <=", value, "updatedonutc");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATEDONUTC in", values, "updatedonutc");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcNotIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATEDONUTC not in", values, "updatedonutc");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATEDONUTC between", value1, value2, "updatedonutc");
            return (Criteria) this;
        }

        public Criteria andUpdatedonutcNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATEDONUTC not between", value1, value2, "updatedonutc");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeIsNull() {
            addCriterion("CREATORDEPTCODE is null");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeIsNotNull() {
            addCriterion("CREATORDEPTCODE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeEqualTo(String value) {
            addCriterion("CREATORDEPTCODE =", value, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeNotEqualTo(String value) {
            addCriterion("CREATORDEPTCODE <>", value, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeGreaterThan(String value) {
            addCriterion("CREATORDEPTCODE >", value, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATORDEPTCODE >=", value, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeLessThan(String value) {
            addCriterion("CREATORDEPTCODE <", value, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeLessThanOrEqualTo(String value) {
            addCriterion("CREATORDEPTCODE <=", value, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeLike(String value) {
            addCriterion("CREATORDEPTCODE like", value, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeNotLike(String value) {
            addCriterion("CREATORDEPTCODE not like", value, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeIn(List<String> values) {
            addCriterion("CREATORDEPTCODE in", values, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeNotIn(List<String> values) {
            addCriterion("CREATORDEPTCODE not in", values, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeBetween(String value1, String value2) {
            addCriterion("CREATORDEPTCODE between", value1, value2, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andCreatordeptcodeNotBetween(String value1, String value2) {
            addCriterion("CREATORDEPTCODE not between", value1, value2, "creatordeptcode");
            return (Criteria) this;
        }

        public Criteria andMerchantcodeIsNull() {
            addCriterion("MERCHANTCODE is null");
            return (Criteria) this;
        }

        public Criteria andMerchantcodeIsNotNull() {
            addCriterion("MERCHANTCODE is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantcodeEqualTo(String value) {
            addCriterion("MERCHANTCODE =", value, "merchantcode");
            return (Criteria) this;
        }

        public Criteria andMerchantcodeNotEqualTo(String value) {
            addCriterion("MERCHANTCODE <>", value, "merchantcode");
            return (Criteria) this;
        }

        public Criteria andMerchantcodeGreaterThan(String value) {
            addCriterion("MERCHANTCODE >", value, "merchantcode");
            return (Criteria) this;
        }

        public Criteria andMerchantcodeGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANTCODE >=", value, "merchantcode");
            return (Criteria) this;
        }

        public Criteria andMerchantcodeLessThan(String value) {
            addCriterion("MERCHANTCODE <", value, "merchantcode");
            return (Criteria) this;
        }

        public Criteria andMerchantcodeLessThanOrEqualTo(String value) {
            addCriterion("MERCHANTCODE <=", value, "merchantcode");
            return (Criteria) this;
        }

        public Criteria andMerchantcodeLike(String value) {
            addCriterion("MERCHANTCODE like", value, "merchantcode");
            return (Criteria) this;
        }

        public Criteria andMerchantcodeNotLike(String value) {
            addCriterion("MERCHANTCODE not like", value, "merchantcode");
            return (Criteria) this;
        }

        public Criteria andMerchantcodeIn(List<String> values) {
            addCriterion("MERCHANTCODE in", values, "merchantcode");
            return (Criteria) this;
        }

        public Criteria andMerchantcodeNotIn(List<String> values) {
            addCriterion("MERCHANTCODE not in", values, "merchantcode");
            return (Criteria) this;
        }

        public Criteria andMerchantcodeBetween(String value1, String value2) {
            addCriterion("MERCHANTCODE between", value1, value2, "merchantcode");
            return (Criteria) this;
        }

        public Criteria andMerchantcodeNotBetween(String value1, String value2) {
            addCriterion("MERCHANTCODE not between", value1, value2, "merchantcode");
            return (Criteria) this;
        }

        public Criteria andSerrotypenIsNull() {
            addCriterion("SERROTYPEN is null");
            return (Criteria) this;
        }

        public Criteria andSerrotypenIsNotNull() {
            addCriterion("SERROTYPEN is not null");
            return (Criteria) this;
        }

        public Criteria andSerrotypenEqualTo(String value) {
            addCriterion("SERROTYPEN =", value, "serrotypen");
            return (Criteria) this;
        }

        public Criteria andSerrotypenNotEqualTo(String value) {
            addCriterion("SERROTYPEN <>", value, "serrotypen");
            return (Criteria) this;
        }

        public Criteria andSerrotypenGreaterThan(String value) {
            addCriterion("SERROTYPEN >", value, "serrotypen");
            return (Criteria) this;
        }

        public Criteria andSerrotypenGreaterThanOrEqualTo(String value) {
            addCriterion("SERROTYPEN >=", value, "serrotypen");
            return (Criteria) this;
        }

        public Criteria andSerrotypenLessThan(String value) {
            addCriterion("SERROTYPEN <", value, "serrotypen");
            return (Criteria) this;
        }

        public Criteria andSerrotypenLessThanOrEqualTo(String value) {
            addCriterion("SERROTYPEN <=", value, "serrotypen");
            return (Criteria) this;
        }

        public Criteria andSerrotypenLike(String value) {
            addCriterion("SERROTYPEN like", value, "serrotypen");
            return (Criteria) this;
        }

        public Criteria andSerrotypenNotLike(String value) {
            addCriterion("SERROTYPEN not like", value, "serrotypen");
            return (Criteria) this;
        }

        public Criteria andSerrotypenIn(List<String> values) {
            addCriterion("SERROTYPEN in", values, "serrotypen");
            return (Criteria) this;
        }

        public Criteria andSerrotypenNotIn(List<String> values) {
            addCriterion("SERROTYPEN not in", values, "serrotypen");
            return (Criteria) this;
        }

        public Criteria andSerrotypenBetween(String value1, String value2) {
            addCriterion("SERROTYPEN between", value1, value2, "serrotypen");
            return (Criteria) this;
        }

        public Criteria andSerrotypenNotBetween(String value1, String value2) {
            addCriterion("SERROTYPEN not between", value1, value2, "serrotypen");
            return (Criteria) this;
        }

        public Criteria andSerrotypencodeIsNull() {
            addCriterion("SERROTYPENCODE is null");
            return (Criteria) this;
        }

        public Criteria andSerrotypencodeIsNotNull() {
            addCriterion("SERROTYPENCODE is not null");
            return (Criteria) this;
        }

        public Criteria andSerrotypencodeEqualTo(String value) {
            addCriterion("SERROTYPENCODE =", value, "serrotypencode");
            return (Criteria) this;
        }

        public Criteria andSerrotypencodeNotEqualTo(String value) {
            addCriterion("SERROTYPENCODE <>", value, "serrotypencode");
            return (Criteria) this;
        }

        public Criteria andSerrotypencodeGreaterThan(String value) {
            addCriterion("SERROTYPENCODE >", value, "serrotypencode");
            return (Criteria) this;
        }

        public Criteria andSerrotypencodeGreaterThanOrEqualTo(String value) {
            addCriterion("SERROTYPENCODE >=", value, "serrotypencode");
            return (Criteria) this;
        }

        public Criteria andSerrotypencodeLessThan(String value) {
            addCriterion("SERROTYPENCODE <", value, "serrotypencode");
            return (Criteria) this;
        }

        public Criteria andSerrotypencodeLessThanOrEqualTo(String value) {
            addCriterion("SERROTYPENCODE <=", value, "serrotypencode");
            return (Criteria) this;
        }

        public Criteria andSerrotypencodeLike(String value) {
            addCriterion("SERROTYPENCODE like", value, "serrotypencode");
            return (Criteria) this;
        }

        public Criteria andSerrotypencodeNotLike(String value) {
            addCriterion("SERROTYPENCODE not like", value, "serrotypencode");
            return (Criteria) this;
        }

        public Criteria andSerrotypencodeIn(List<String> values) {
            addCriterion("SERROTYPENCODE in", values, "serrotypencode");
            return (Criteria) this;
        }

        public Criteria andSerrotypencodeNotIn(List<String> values) {
            addCriterion("SERROTYPENCODE not in", values, "serrotypencode");
            return (Criteria) this;
        }

        public Criteria andSerrotypencodeBetween(String value1, String value2) {
            addCriterion("SERROTYPENCODE between", value1, value2, "serrotypencode");
            return (Criteria) this;
        }

        public Criteria andSerrotypencodeNotBetween(String value1, String value2) {
            addCriterion("SERROTYPENCODE not between", value1, value2, "serrotypencode");
            return (Criteria) this;
        }

        public Criteria andAgmatyprnIsNull() {
            addCriterion("AGMATYPRN is null");
            return (Criteria) this;
        }

        public Criteria andAgmatyprnIsNotNull() {
            addCriterion("AGMATYPRN is not null");
            return (Criteria) this;
        }

        public Criteria andAgmatyprnEqualTo(String value) {
            addCriterion("AGMATYPRN =", value, "agmatyprn");
            return (Criteria) this;
        }

        public Criteria andAgmatyprnNotEqualTo(String value) {
            addCriterion("AGMATYPRN <>", value, "agmatyprn");
            return (Criteria) this;
        }

        public Criteria andAgmatyprnGreaterThan(String value) {
            addCriterion("AGMATYPRN >", value, "agmatyprn");
            return (Criteria) this;
        }

        public Criteria andAgmatyprnGreaterThanOrEqualTo(String value) {
            addCriterion("AGMATYPRN >=", value, "agmatyprn");
            return (Criteria) this;
        }

        public Criteria andAgmatyprnLessThan(String value) {
            addCriterion("AGMATYPRN <", value, "agmatyprn");
            return (Criteria) this;
        }

        public Criteria andAgmatyprnLessThanOrEqualTo(String value) {
            addCriterion("AGMATYPRN <=", value, "agmatyprn");
            return (Criteria) this;
        }

        public Criteria andAgmatyprnLike(String value) {
            addCriterion("AGMATYPRN like", value, "agmatyprn");
            return (Criteria) this;
        }

        public Criteria andAgmatyprnNotLike(String value) {
            addCriterion("AGMATYPRN not like", value, "agmatyprn");
            return (Criteria) this;
        }

        public Criteria andAgmatyprnIn(List<String> values) {
            addCriterion("AGMATYPRN in", values, "agmatyprn");
            return (Criteria) this;
        }

        public Criteria andAgmatyprnNotIn(List<String> values) {
            addCriterion("AGMATYPRN not in", values, "agmatyprn");
            return (Criteria) this;
        }

        public Criteria andAgmatyprnBetween(String value1, String value2) {
            addCriterion("AGMATYPRN between", value1, value2, "agmatyprn");
            return (Criteria) this;
        }

        public Criteria andAgmatyprnNotBetween(String value1, String value2) {
            addCriterion("AGMATYPRN not between", value1, value2, "agmatyprn");
            return (Criteria) this;
        }

        public Criteria andAgmatyprncodeIsNull() {
            addCriterion("AGMATYPRNCODE is null");
            return (Criteria) this;
        }

        public Criteria andAgmatyprncodeIsNotNull() {
            addCriterion("AGMATYPRNCODE is not null");
            return (Criteria) this;
        }

        public Criteria andAgmatyprncodeEqualTo(String value) {
            addCriterion("AGMATYPRNCODE =", value, "agmatyprncode");
            return (Criteria) this;
        }

        public Criteria andAgmatyprncodeNotEqualTo(String value) {
            addCriterion("AGMATYPRNCODE <>", value, "agmatyprncode");
            return (Criteria) this;
        }

        public Criteria andAgmatyprncodeGreaterThan(String value) {
            addCriterion("AGMATYPRNCODE >", value, "agmatyprncode");
            return (Criteria) this;
        }

        public Criteria andAgmatyprncodeGreaterThanOrEqualTo(String value) {
            addCriterion("AGMATYPRNCODE >=", value, "agmatyprncode");
            return (Criteria) this;
        }

        public Criteria andAgmatyprncodeLessThan(String value) {
            addCriterion("AGMATYPRNCODE <", value, "agmatyprncode");
            return (Criteria) this;
        }

        public Criteria andAgmatyprncodeLessThanOrEqualTo(String value) {
            addCriterion("AGMATYPRNCODE <=", value, "agmatyprncode");
            return (Criteria) this;
        }

        public Criteria andAgmatyprncodeLike(String value) {
            addCriterion("AGMATYPRNCODE like", value, "agmatyprncode");
            return (Criteria) this;
        }

        public Criteria andAgmatyprncodeNotLike(String value) {
            addCriterion("AGMATYPRNCODE not like", value, "agmatyprncode");
            return (Criteria) this;
        }

        public Criteria andAgmatyprncodeIn(List<String> values) {
            addCriterion("AGMATYPRNCODE in", values, "agmatyprncode");
            return (Criteria) this;
        }

        public Criteria andAgmatyprncodeNotIn(List<String> values) {
            addCriterion("AGMATYPRNCODE not in", values, "agmatyprncode");
            return (Criteria) this;
        }

        public Criteria andAgmatyprncodeBetween(String value1, String value2) {
            addCriterion("AGMATYPRNCODE between", value1, value2, "agmatyprncode");
            return (Criteria) this;
        }

        public Criteria andAgmatyprncodeNotBetween(String value1, String value2) {
            addCriterion("AGMATYPRNCODE not between", value1, value2, "agmatyprncode");
            return (Criteria) this;
        }

        public Criteria andDistanceIsNull() {
            addCriterion("DISTANCE is null");
            return (Criteria) this;
        }

        public Criteria andDistanceIsNotNull() {
            addCriterion("DISTANCE is not null");
            return (Criteria) this;
        }

        public Criteria andDistanceEqualTo(String value) {
            addCriterion("DISTANCE =", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceNotEqualTo(String value) {
            addCriterion("DISTANCE <>", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceGreaterThan(String value) {
            addCriterion("DISTANCE >", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceGreaterThanOrEqualTo(String value) {
            addCriterion("DISTANCE >=", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceLessThan(String value) {
            addCriterion("DISTANCE <", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceLessThanOrEqualTo(String value) {
            addCriterion("DISTANCE <=", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceLike(String value) {
            addCriterion("DISTANCE like", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceNotLike(String value) {
            addCriterion("DISTANCE not like", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceIn(List<String> values) {
            addCriterion("DISTANCE in", values, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceNotIn(List<String> values) {
            addCriterion("DISTANCE not in", values, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceBetween(String value1, String value2) {
            addCriterion("DISTANCE between", value1, value2, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceNotBetween(String value1, String value2) {
            addCriterion("DISTANCE not between", value1, value2, "distance");
            return (Criteria) this;
        }

        public Criteria andServiceunitIsNull() {
            addCriterion("SERVICEUNIT is null");
            return (Criteria) this;
        }

        public Criteria andServiceunitIsNotNull() {
            addCriterion("SERVICEUNIT is not null");
            return (Criteria) this;
        }

        public Criteria andServiceunitEqualTo(String value) {
            addCriterion("SERVICEUNIT =", value, "serviceunit");
            return (Criteria) this;
        }

        public Criteria andServiceunitNotEqualTo(String value) {
            addCriterion("SERVICEUNIT <>", value, "serviceunit");
            return (Criteria) this;
        }

        public Criteria andServiceunitGreaterThan(String value) {
            addCriterion("SERVICEUNIT >", value, "serviceunit");
            return (Criteria) this;
        }

        public Criteria andServiceunitGreaterThanOrEqualTo(String value) {
            addCriterion("SERVICEUNIT >=", value, "serviceunit");
            return (Criteria) this;
        }

        public Criteria andServiceunitLessThan(String value) {
            addCriterion("SERVICEUNIT <", value, "serviceunit");
            return (Criteria) this;
        }

        public Criteria andServiceunitLessThanOrEqualTo(String value) {
            addCriterion("SERVICEUNIT <=", value, "serviceunit");
            return (Criteria) this;
        }

        public Criteria andServiceunitLike(String value) {
            addCriterion("SERVICEUNIT like", value, "serviceunit");
            return (Criteria) this;
        }

        public Criteria andServiceunitNotLike(String value) {
            addCriterion("SERVICEUNIT not like", value, "serviceunit");
            return (Criteria) this;
        }

        public Criteria andServiceunitIn(List<String> values) {
            addCriterion("SERVICEUNIT in", values, "serviceunit");
            return (Criteria) this;
        }

        public Criteria andServiceunitNotIn(List<String> values) {
            addCriterion("SERVICEUNIT not in", values, "serviceunit");
            return (Criteria) this;
        }

        public Criteria andServiceunitBetween(String value1, String value2) {
            addCriterion("SERVICEUNIT between", value1, value2, "serviceunit");
            return (Criteria) this;
        }

        public Criteria andServiceunitNotBetween(String value1, String value2) {
            addCriterion("SERVICEUNIT not between", value1, value2, "serviceunit");
            return (Criteria) this;
        }

        public Criteria andFoodkindcodeIsNull() {
            addCriterion("FOODKINDCODE is null");
            return (Criteria) this;
        }

        public Criteria andFoodkindcodeIsNotNull() {
            addCriterion("FOODKINDCODE is not null");
            return (Criteria) this;
        }

        public Criteria andFoodkindcodeEqualTo(String value) {
            addCriterion("FOODKINDCODE =", value, "foodkindcode");
            return (Criteria) this;
        }

        public Criteria andFoodkindcodeNotEqualTo(String value) {
            addCriterion("FOODKINDCODE <>", value, "foodkindcode");
            return (Criteria) this;
        }

        public Criteria andFoodkindcodeGreaterThan(String value) {
            addCriterion("FOODKINDCODE >", value, "foodkindcode");
            return (Criteria) this;
        }

        public Criteria andFoodkindcodeGreaterThanOrEqualTo(String value) {
            addCriterion("FOODKINDCODE >=", value, "foodkindcode");
            return (Criteria) this;
        }

        public Criteria andFoodkindcodeLessThan(String value) {
            addCriterion("FOODKINDCODE <", value, "foodkindcode");
            return (Criteria) this;
        }

        public Criteria andFoodkindcodeLessThanOrEqualTo(String value) {
            addCriterion("FOODKINDCODE <=", value, "foodkindcode");
            return (Criteria) this;
        }

        public Criteria andFoodkindcodeLike(String value) {
            addCriterion("FOODKINDCODE like", value, "foodkindcode");
            return (Criteria) this;
        }

        public Criteria andFoodkindcodeNotLike(String value) {
            addCriterion("FOODKINDCODE not like", value, "foodkindcode");
            return (Criteria) this;
        }

        public Criteria andFoodkindcodeIn(List<String> values) {
            addCriterion("FOODKINDCODE in", values, "foodkindcode");
            return (Criteria) this;
        }

        public Criteria andFoodkindcodeNotIn(List<String> values) {
            addCriterion("FOODKINDCODE not in", values, "foodkindcode");
            return (Criteria) this;
        }

        public Criteria andFoodkindcodeBetween(String value1, String value2) {
            addCriterion("FOODKINDCODE between", value1, value2, "foodkindcode");
            return (Criteria) this;
        }

        public Criteria andFoodkindcodeNotBetween(String value1, String value2) {
            addCriterion("FOODKINDCODE not between", value1, value2, "foodkindcode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ZLNF_SERVICEPROGRAM
     *
     * @mbggenerated do_not_delete_during_merge Fri Aug 18 11:52:30 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ZLNF_SERVICEPROGRAM
     *
     * @mbggenerated Fri Aug 18 11:52:30 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}