package com.vt.fencing.model;

import java.util.Date;

public class ZlnfMessageInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_MESSAGEINFO.ID
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_MESSAGEINFO.MESSAGEINFOCODE
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    private String messageinfocode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_MESSAGEINFO.USERCODE
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    private String usercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_MESSAGEINFO.TITLE
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_MESSAGEINFO.SHORTCONTENT
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    private String shortcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_MESSAGEINFO.CONTENT
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_MESSAGEINFO.SENDUSERCODE
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    private String sendusercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_MESSAGEINFO.SENDUSERNAME
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    private String sendusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_MESSAGEINFO.MESSAGETYPECODE
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    private String messagetypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_MESSAGEINFO.SENDTIME
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    private Date sendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_MESSAGEINFO.CREATEDONUTC
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    private Date createdonutc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_MESSAGEINFO.CREATOR
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_MESSAGEINFO.ISAUDIT
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    private String isaudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_MESSAGEINFO.ISDELETED
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    private String isdeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_MESSAGEINFO.MODIFIER
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_MESSAGEINFO.UPDATEDONUTC
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    private Date updatedonutc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_MESSAGEINFO.CREATORDEPTCODE
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    private String creatordeptcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_MESSAGEINFO.ID
     *
     * @return the value of ZLNF_MESSAGEINFO.ID
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_MESSAGEINFO.ID
     *
     * @param id the value for ZLNF_MESSAGEINFO.ID
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_MESSAGEINFO.MESSAGEINFOCODE
     *
     * @return the value of ZLNF_MESSAGEINFO.MESSAGEINFOCODE
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public String getMessageinfocode() {
        return messageinfocode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_MESSAGEINFO.MESSAGEINFOCODE
     *
     * @param messageinfocode the value for ZLNF_MESSAGEINFO.MESSAGEINFOCODE
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public void setMessageinfocode(String messageinfocode) {
        this.messageinfocode = messageinfocode == null ? null : messageinfocode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_MESSAGEINFO.USERCODE
     *
     * @return the value of ZLNF_MESSAGEINFO.USERCODE
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_MESSAGEINFO.USERCODE
     *
     * @param usercode the value for ZLNF_MESSAGEINFO.USERCODE
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode == null ? null : usercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_MESSAGEINFO.TITLE
     *
     * @return the value of ZLNF_MESSAGEINFO.TITLE
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_MESSAGEINFO.TITLE
     *
     * @param title the value for ZLNF_MESSAGEINFO.TITLE
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_MESSAGEINFO.SHORTCONTENT
     *
     * @return the value of ZLNF_MESSAGEINFO.SHORTCONTENT
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public String getShortcontent() {
        return shortcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_MESSAGEINFO.SHORTCONTENT
     *
     * @param shortcontent the value for ZLNF_MESSAGEINFO.SHORTCONTENT
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public void setShortcontent(String shortcontent) {
        this.shortcontent = shortcontent == null ? null : shortcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_MESSAGEINFO.CONTENT
     *
     * @return the value of ZLNF_MESSAGEINFO.CONTENT
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_MESSAGEINFO.CONTENT
     *
     * @param content the value for ZLNF_MESSAGEINFO.CONTENT
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_MESSAGEINFO.SENDUSERCODE
     *
     * @return the value of ZLNF_MESSAGEINFO.SENDUSERCODE
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public String getSendusercode() {
        return sendusercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_MESSAGEINFO.SENDUSERCODE
     *
     * @param sendusercode the value for ZLNF_MESSAGEINFO.SENDUSERCODE
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public void setSendusercode(String sendusercode) {
        this.sendusercode = sendusercode == null ? null : sendusercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_MESSAGEINFO.SENDUSERNAME
     *
     * @return the value of ZLNF_MESSAGEINFO.SENDUSERNAME
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public String getSendusername() {
        return sendusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_MESSAGEINFO.SENDUSERNAME
     *
     * @param sendusername the value for ZLNF_MESSAGEINFO.SENDUSERNAME
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public void setSendusername(String sendusername) {
        this.sendusername = sendusername == null ? null : sendusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_MESSAGEINFO.MESSAGETYPECODE
     *
     * @return the value of ZLNF_MESSAGEINFO.MESSAGETYPECODE
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public String getMessagetypecode() {
        return messagetypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_MESSAGEINFO.MESSAGETYPECODE
     *
     * @param messagetypecode the value for ZLNF_MESSAGEINFO.MESSAGETYPECODE
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public void setMessagetypecode(String messagetypecode) {
        this.messagetypecode = messagetypecode == null ? null : messagetypecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_MESSAGEINFO.SENDTIME
     *
     * @return the value of ZLNF_MESSAGEINFO.SENDTIME
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_MESSAGEINFO.SENDTIME
     *
     * @param sendtime the value for ZLNF_MESSAGEINFO.SENDTIME
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_MESSAGEINFO.CREATEDONUTC
     *
     * @return the value of ZLNF_MESSAGEINFO.CREATEDONUTC
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public Date getCreatedonutc() {
        return createdonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_MESSAGEINFO.CREATEDONUTC
     *
     * @param createdonutc the value for ZLNF_MESSAGEINFO.CREATEDONUTC
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public void setCreatedonutc(Date createdonutc) {
        this.createdonutc = createdonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_MESSAGEINFO.CREATOR
     *
     * @return the value of ZLNF_MESSAGEINFO.CREATOR
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_MESSAGEINFO.CREATOR
     *
     * @param creator the value for ZLNF_MESSAGEINFO.CREATOR
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_MESSAGEINFO.ISAUDIT
     *
     * @return the value of ZLNF_MESSAGEINFO.ISAUDIT
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public String getIsaudit() {
        return isaudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_MESSAGEINFO.ISAUDIT
     *
     * @param isaudit the value for ZLNF_MESSAGEINFO.ISAUDIT
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public void setIsaudit(String isaudit) {
        this.isaudit = isaudit == null ? null : isaudit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_MESSAGEINFO.ISDELETED
     *
     * @return the value of ZLNF_MESSAGEINFO.ISDELETED
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public String getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_MESSAGEINFO.ISDELETED
     *
     * @param isdeleted the value for ZLNF_MESSAGEINFO.ISDELETED
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public void setIsdeleted(String isdeleted) {
        this.isdeleted = isdeleted == null ? null : isdeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_MESSAGEINFO.MODIFIER
     *
     * @return the value of ZLNF_MESSAGEINFO.MODIFIER
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_MESSAGEINFO.MODIFIER
     *
     * @param modifier the value for ZLNF_MESSAGEINFO.MODIFIER
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_MESSAGEINFO.UPDATEDONUTC
     *
     * @return the value of ZLNF_MESSAGEINFO.UPDATEDONUTC
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public Date getUpdatedonutc() {
        return updatedonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_MESSAGEINFO.UPDATEDONUTC
     *
     * @param updatedonutc the value for ZLNF_MESSAGEINFO.UPDATEDONUTC
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public void setUpdatedonutc(Date updatedonutc) {
        this.updatedonutc = updatedonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_MESSAGEINFO.CREATORDEPTCODE
     *
     * @return the value of ZLNF_MESSAGEINFO.CREATORDEPTCODE
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public String getCreatordeptcode() {
        return creatordeptcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_MESSAGEINFO.CREATORDEPTCODE
     *
     * @param creatordeptcode the value for ZLNF_MESSAGEINFO.CREATORDEPTCODE
     *
     * @mbggenerated Thu Aug 31 18:25:19 CST 2017
     */
    public void setCreatordeptcode(String creatordeptcode) {
        this.creatordeptcode = creatordeptcode == null ? null : creatordeptcode.trim();
    }
}