package com.vt.fencing.model;

import java.util.Date;
import java.util.List;

public class ZlnfUserdiscuss {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.ID
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.DISCUSSCODE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private String discusscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.DISCUSSCONTENT
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private String discusscontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.MOBEIL
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private String mobeil;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.DISCUSSTIME
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private Date discusstime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.SERVERCODE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private String servercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.SERVERTYPE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private String servertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.COOPNAME
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private String coopname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.COOPCODE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private String coopcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.DISLEVEL
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private String dislevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.MERCHANTCODE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private String merchantcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.MERCHANTNAME
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private String merchantname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.CREATEDONUTC
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private Date createdonutc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.CREATOR
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.ISAUDIT
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private String isaudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.ISDELETED
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private String isdeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.MODIFIER
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.UPDATEDONUTC
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private Date updatedonutc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.CREATORDEPTCODE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private String creatordeptcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.BEEVALUATED
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private String beevaluated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.CREATORCODE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private String creatorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_USERDISCUSS.EVALUATETYPE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    private String evaluatetype;

    /**
     * 图片集合
     */
    private List<ZlnfAnnex> annexList;

    /**
     * 图片集合
     */
    private String httppath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.ID
     *
     * @return the value of ZLNF_USERDISCUSS.ID
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.ID
     *
     * @param id the value for ZLNF_USERDISCUSS.ID
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.DISCUSSCODE
     *
     * @return the value of ZLNF_USERDISCUSS.DISCUSSCODE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public String getDiscusscode() {
        return discusscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.DISCUSSCODE
     *
     * @param discusscode the value for ZLNF_USERDISCUSS.DISCUSSCODE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setDiscusscode(String discusscode) {
        this.discusscode = discusscode == null ? null : discusscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.DISCUSSCONTENT
     *
     * @return the value of ZLNF_USERDISCUSS.DISCUSSCONTENT
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public String getDiscusscontent() {
        return discusscontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.DISCUSSCONTENT
     *
     * @param discusscontent the value for ZLNF_USERDISCUSS.DISCUSSCONTENT
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setDiscusscontent(String discusscontent) {
        this.discusscontent = discusscontent == null ? null : discusscontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.MOBEIL
     *
     * @return the value of ZLNF_USERDISCUSS.MOBEIL
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public String getMobeil() {
        return mobeil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.MOBEIL
     *
     * @param mobeil the value for ZLNF_USERDISCUSS.MOBEIL
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setMobeil(String mobeil) {
        this.mobeil = mobeil == null ? null : mobeil.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.DISCUSSTIME
     *
     * @return the value of ZLNF_USERDISCUSS.DISCUSSTIME
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public Date getDiscusstime() {
        return discusstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.DISCUSSTIME
     *
     * @param discusstime the value for ZLNF_USERDISCUSS.DISCUSSTIME
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setDiscusstime(Date discusstime) {
        this.discusstime = discusstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.SERVERCODE
     *
     * @return the value of ZLNF_USERDISCUSS.SERVERCODE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public String getServercode() {
        return servercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.SERVERCODE
     *
     * @param servercode the value for ZLNF_USERDISCUSS.SERVERCODE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setServercode(String servercode) {
        this.servercode = servercode == null ? null : servercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.SERVERTYPE
     *
     * @return the value of ZLNF_USERDISCUSS.SERVERTYPE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public String getServertype() {
        return servertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.SERVERTYPE
     *
     * @param servertype the value for ZLNF_USERDISCUSS.SERVERTYPE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setServertype(String servertype) {
        this.servertype = servertype == null ? null : servertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.COOPNAME
     *
     * @return the value of ZLNF_USERDISCUSS.COOPNAME
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public String getCoopname() {
        return coopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.COOPNAME
     *
     * @param coopname the value for ZLNF_USERDISCUSS.COOPNAME
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setCoopname(String coopname) {
        this.coopname = coopname == null ? null : coopname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.COOPCODE
     *
     * @return the value of ZLNF_USERDISCUSS.COOPCODE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public String getCoopcode() {
        return coopcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.COOPCODE
     *
     * @param coopcode the value for ZLNF_USERDISCUSS.COOPCODE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setCoopcode(String coopcode) {
        this.coopcode = coopcode == null ? null : coopcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.DISLEVEL
     *
     * @return the value of ZLNF_USERDISCUSS.DISLEVEL
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public String getDislevel() {
        return dislevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.DISLEVEL
     *
     * @param dislevel the value for ZLNF_USERDISCUSS.DISLEVEL
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setDislevel(String dislevel) {
        this.dislevel = dislevel == null ? null : dislevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.MERCHANTCODE
     *
     * @return the value of ZLNF_USERDISCUSS.MERCHANTCODE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public String getMerchantcode() {
        return merchantcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.MERCHANTCODE
     *
     * @param merchantcode the value for ZLNF_USERDISCUSS.MERCHANTCODE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setMerchantcode(String merchantcode) {
        this.merchantcode = merchantcode == null ? null : merchantcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.MERCHANTNAME
     *
     * @return the value of ZLNF_USERDISCUSS.MERCHANTNAME
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public String getMerchantname() {
        return merchantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.MERCHANTNAME
     *
     * @param merchantname the value for ZLNF_USERDISCUSS.MERCHANTNAME
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setMerchantname(String merchantname) {
        this.merchantname = merchantname == null ? null : merchantname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.CREATEDONUTC
     *
     * @return the value of ZLNF_USERDISCUSS.CREATEDONUTC
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public Date getCreatedonutc() {
        return createdonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.CREATEDONUTC
     *
     * @param createdonutc the value for ZLNF_USERDISCUSS.CREATEDONUTC
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setCreatedonutc(Date createdonutc) {
        this.createdonutc = createdonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.CREATOR
     *
     * @return the value of ZLNF_USERDISCUSS.CREATOR
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.CREATOR
     *
     * @param creator the value for ZLNF_USERDISCUSS.CREATOR
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.ISAUDIT
     *
     * @return the value of ZLNF_USERDISCUSS.ISAUDIT
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public String getIsaudit() {
        return isaudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.ISAUDIT
     *
     * @param isaudit the value for ZLNF_USERDISCUSS.ISAUDIT
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setIsaudit(String isaudit) {
        this.isaudit = isaudit == null ? null : isaudit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.ISDELETED
     *
     * @return the value of ZLNF_USERDISCUSS.ISDELETED
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public String getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.ISDELETED
     *
     * @param isdeleted the value for ZLNF_USERDISCUSS.ISDELETED
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setIsdeleted(String isdeleted) {
        this.isdeleted = isdeleted == null ? null : isdeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.MODIFIER
     *
     * @return the value of ZLNF_USERDISCUSS.MODIFIER
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.MODIFIER
     *
     * @param modifier the value for ZLNF_USERDISCUSS.MODIFIER
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.UPDATEDONUTC
     *
     * @return the value of ZLNF_USERDISCUSS.UPDATEDONUTC
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public Date getUpdatedonutc() {
        return updatedonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.UPDATEDONUTC
     *
     * @param updatedonutc the value for ZLNF_USERDISCUSS.UPDATEDONUTC
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setUpdatedonutc(Date updatedonutc) {
        this.updatedonutc = updatedonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.CREATORDEPTCODE
     *
     * @return the value of ZLNF_USERDISCUSS.CREATORDEPTCODE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public String getCreatordeptcode() {
        return creatordeptcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.CREATORDEPTCODE
     *
     * @param creatordeptcode the value for ZLNF_USERDISCUSS.CREATORDEPTCODE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setCreatordeptcode(String creatordeptcode) {
        this.creatordeptcode = creatordeptcode == null ? null : creatordeptcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.BEEVALUATED
     *
     * @return the value of ZLNF_USERDISCUSS.BEEVALUATED
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public String getBeevaluated() {
        return beevaluated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.BEEVALUATED
     *
     * @param beevaluated the value for ZLNF_USERDISCUSS.BEEVALUATED
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setBeevaluated(String beevaluated) {
        this.beevaluated = beevaluated == null ? null : beevaluated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.CREATORCODE
     *
     * @return the value of ZLNF_USERDISCUSS.CREATORCODE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public String getCreatorcode() {
        return creatorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.CREATORCODE
     *
     * @param creatorcode the value for ZLNF_USERDISCUSS.CREATORCODE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setCreatorcode(String creatorcode) {
        this.creatorcode = creatorcode == null ? null : creatorcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_USERDISCUSS.EVALUATETYPE
     *
     * @return the value of ZLNF_USERDISCUSS.EVALUATETYPE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public String getEvaluatetype() {
        return evaluatetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_USERDISCUSS.EVALUATETYPE
     *
     * @param evaluatetype the value for ZLNF_USERDISCUSS.EVALUATETYPE
     *
     * @mbggenerated Mon Aug 21 15:31:49 CST 2017
     */
    public void setEvaluatetype(String evaluatetype) {
        this.evaluatetype = evaluatetype == null ? null : evaluatetype.trim();
    }

	public List<ZlnfAnnex> getAnnexList() {
		return annexList;
	}

	public void setAnnexList(List<ZlnfAnnex> annexList) {
		this.annexList = annexList;
	}

	public String getHttppath() {
		return httppath;
	}

	public void setHttppath(String httppath) {
		this.httppath = httppath;
	}
	
}