package com.vt.fencing.request;

import java.util.Date;

public class ZlnfApppiontOrderTimeRequest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.ID
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.APPIONTORDERCODE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private String appiontordercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.APPIONTTIME
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private Date appionttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.SELLNUM
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private String sellnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.FOODCODE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private String foodcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.STATE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.FOODKIND
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private String foodkind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.FOODUNIT
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private String foodunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.FOODLEVEL
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private String foodlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.FOODNAME
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private String foodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.COOPCODE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private String coopcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.CREATEDONUTC
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private Date createdonutc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.CREATOR
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.ISAUDIT
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private String isaudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.ISDELETED
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private String isdeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.MODIFIER
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.UPDATEDONUTC
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private Date updatedonutc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.CREATORDEPTCODE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private String creatordeptcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.WATER
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private Double water;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.CREATORCODE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private String creatorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.TIMESLOT
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private String timeslot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.FOODKINDCODE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private String foodkindcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.FOODLEVELCODE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private String foodlevelcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.REALSELLNUM
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private String realsellnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.FEEDBACKPERSON
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private String feedbackperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_APPPIONTORDERTIME.FEEDBACKTIME
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    private String feedbacktime;
    
    /**
     * 页数
     */
    private String number;
    
    /**
     * 用户名称
     */
    private String username;
    
    /**
     * 用户编号
     */
    private String usercode;

    /**
     * 用户角色
     */
    private String roletype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.ID
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.ID
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.ID
     *
     * @param id the value for ZLNF_APPPIONTORDERTIME.ID
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.APPIONTORDERCODE
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.APPIONTORDERCODE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public String getAppiontordercode() {
        return appiontordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.APPIONTORDERCODE
     *
     * @param appiontordercode the value for ZLNF_APPPIONTORDERTIME.APPIONTORDERCODE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setAppiontordercode(String appiontordercode) {
        this.appiontordercode = appiontordercode == null ? null : appiontordercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.APPIONTTIME
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.APPIONTTIME
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public Date getAppionttime() {
        return appionttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.APPIONTTIME
     *
     * @param appionttime the value for ZLNF_APPPIONTORDERTIME.APPIONTTIME
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setAppionttime(Date appionttime) {
        this.appionttime = appionttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.SELLNUM
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.SELLNUM
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public String getSellnum() {
        return sellnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.SELLNUM
     *
     * @param sellnum the value for ZLNF_APPPIONTORDERTIME.SELLNUM
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setSellnum(String sellnum) {
        this.sellnum = sellnum == null ? null : sellnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.FOODCODE
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.FOODCODE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public String getFoodcode() {
        return foodcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.FOODCODE
     *
     * @param foodcode the value for ZLNF_APPPIONTORDERTIME.FOODCODE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setFoodcode(String foodcode) {
        this.foodcode = foodcode == null ? null : foodcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.STATE
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.STATE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.STATE
     *
     * @param state the value for ZLNF_APPPIONTORDERTIME.STATE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.FOODKIND
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.FOODKIND
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public String getFoodkind() {
        return foodkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.FOODKIND
     *
     * @param foodkind the value for ZLNF_APPPIONTORDERTIME.FOODKIND
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setFoodkind(String foodkind) {
        this.foodkind = foodkind == null ? null : foodkind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.FOODUNIT
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.FOODUNIT
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public String getFoodunit() {
        return foodunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.FOODUNIT
     *
     * @param foodunit the value for ZLNF_APPPIONTORDERTIME.FOODUNIT
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setFoodunit(String foodunit) {
        this.foodunit = foodunit == null ? null : foodunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.FOODLEVEL
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.FOODLEVEL
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public String getFoodlevel() {
        return foodlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.FOODLEVEL
     *
     * @param foodlevel the value for ZLNF_APPPIONTORDERTIME.FOODLEVEL
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setFoodlevel(String foodlevel) {
        this.foodlevel = foodlevel == null ? null : foodlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.FOODNAME
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.FOODNAME
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public String getFoodname() {
        return foodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.FOODNAME
     *
     * @param foodname the value for ZLNF_APPPIONTORDERTIME.FOODNAME
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setFoodname(String foodname) {
        this.foodname = foodname == null ? null : foodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.COOPCODE
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.COOPCODE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public String getCoopcode() {
        return coopcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.COOPCODE
     *
     * @param coopcode the value for ZLNF_APPPIONTORDERTIME.COOPCODE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setCoopcode(String coopcode) {
        this.coopcode = coopcode == null ? null : coopcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.CREATEDONUTC
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.CREATEDONUTC
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public Date getCreatedonutc() {
        return createdonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.CREATEDONUTC
     *
     * @param createdonutc the value for ZLNF_APPPIONTORDERTIME.CREATEDONUTC
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setCreatedonutc(Date createdonutc) {
        this.createdonutc = createdonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.CREATOR
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.CREATOR
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.CREATOR
     *
     * @param creator the value for ZLNF_APPPIONTORDERTIME.CREATOR
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.ISAUDIT
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.ISAUDIT
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public String getIsaudit() {
        return isaudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.ISAUDIT
     *
     * @param isaudit the value for ZLNF_APPPIONTORDERTIME.ISAUDIT
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setIsaudit(String isaudit) {
        this.isaudit = isaudit == null ? null : isaudit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.ISDELETED
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.ISDELETED
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public String getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.ISDELETED
     *
     * @param isdeleted the value for ZLNF_APPPIONTORDERTIME.ISDELETED
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setIsdeleted(String isdeleted) {
        this.isdeleted = isdeleted == null ? null : isdeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.MODIFIER
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.MODIFIER
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.MODIFIER
     *
     * @param modifier the value for ZLNF_APPPIONTORDERTIME.MODIFIER
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.UPDATEDONUTC
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.UPDATEDONUTC
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public Date getUpdatedonutc() {
        return updatedonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.UPDATEDONUTC
     *
     * @param updatedonutc the value for ZLNF_APPPIONTORDERTIME.UPDATEDONUTC
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setUpdatedonutc(Date updatedonutc) {
        this.updatedonutc = updatedonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.CREATORDEPTCODE
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.CREATORDEPTCODE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public String getCreatordeptcode() {
        return creatordeptcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.CREATORDEPTCODE
     *
     * @param creatordeptcode the value for ZLNF_APPPIONTORDERTIME.CREATORDEPTCODE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setCreatordeptcode(String creatordeptcode) {
        this.creatordeptcode = creatordeptcode == null ? null : creatordeptcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.WATER
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.WATER
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public Double getWater() {
        return water;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.WATER
     *
     * @param water the value for ZLNF_APPPIONTORDERTIME.WATER
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setWater(Double water) {
        this.water = water;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.CREATORCODE
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.CREATORCODE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public String getCreatorcode() {
        return creatorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.CREATORCODE
     *
     * @param creatorcode the value for ZLNF_APPPIONTORDERTIME.CREATORCODE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setCreatorcode(String creatorcode) {
        this.creatorcode = creatorcode == null ? null : creatorcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.TIMESLOT
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.TIMESLOT
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public String getTimeslot() {
        return timeslot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.TIMESLOT
     *
     * @param timeslot the value for ZLNF_APPPIONTORDERTIME.TIMESLOT
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setTimeslot(String timeslot) {
        this.timeslot = timeslot == null ? null : timeslot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.FOODKINDCODE
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.FOODKINDCODE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public String getFoodkindcode() {
        return foodkindcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.FOODKINDCODE
     *
     * @param foodkindcode the value for ZLNF_APPPIONTORDERTIME.FOODKINDCODE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setFoodkindcode(String foodkindcode) {
        this.foodkindcode = foodkindcode == null ? null : foodkindcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.FOODLEVELCODE
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.FOODLEVELCODE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public String getFoodlevelcode() {
        return foodlevelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.FOODLEVELCODE
     *
     * @param foodlevelcode the value for ZLNF_APPPIONTORDERTIME.FOODLEVELCODE
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setFoodlevelcode(String foodlevelcode) {
        this.foodlevelcode = foodlevelcode == null ? null : foodlevelcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.REALSELLNUM
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.REALSELLNUM
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public String getRealsellnum() {
        return realsellnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.REALSELLNUM
     *
     * @param realsellnum the value for ZLNF_APPPIONTORDERTIME.REALSELLNUM
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setRealsellnum(String realsellnum) {
        this.realsellnum = realsellnum == null ? null : realsellnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.FEEDBACKPERSON
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.FEEDBACKPERSON
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public String getFeedbackperson() {
        return feedbackperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.FEEDBACKPERSON
     *
     * @param feedbackperson the value for ZLNF_APPPIONTORDERTIME.FEEDBACKPERSON
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setFeedbackperson(String feedbackperson) {
        this.feedbackperson = feedbackperson == null ? null : feedbackperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_APPPIONTORDERTIME.FEEDBACKTIME
     *
     * @return the value of ZLNF_APPPIONTORDERTIME.FEEDBACKTIME
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public String getFeedbacktime() {
        return feedbacktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_APPPIONTORDERTIME.FEEDBACKTIME
     *
     * @param feedbacktime the value for ZLNF_APPPIONTORDERTIME.FEEDBACKTIME
     *
     * @mbggenerated Fri Sep 01 10:07:31 CST 2017
     */
    public void setFeedbacktime(String feedbacktime) {
        this.feedbacktime = feedbacktime == null ? null : feedbacktime.trim();
    }

	public String getNumber() {
		return number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getUsercode() {
		return usercode;
	}

	public void setUsercode(String usercode) {
		this.usercode = usercode;
	}

	public String getRoletype() {
		return roletype;
	}

	public void setRoletype(String roletype) {
		this.roletype = roletype;
	}
    
}