package com.vt.fencing.request;

import java.util.Date;

public class ZlnfAnnexRequest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_ANNEX.ID
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_ANNEX.DEPTCODE
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    private String deptcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_ANNEX.ANNEXCODE
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    private String annexcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_ANNEX.ANNEXNAME
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    private String annexname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_ANNEX.ANNEXPATH
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    private String annexpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_ANNEX.DEPTTYPE
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    private String depttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_ANNEX.PICTURESTYPE
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    private String picturestype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_ANNEX.ISDEFAULT
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    private String isdefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_ANNEX.CREATEDONUTC
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    private Date createdonutc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_ANNEX.CREATOR
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_ANNEX.ISAUDIT
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    private String isaudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_ANNEX.ISDELETED
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    private String isdeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_ANNEX.MODIFIER
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_ANNEX.UPDATEDONUTC
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    private Date updatedonutc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_ANNEX.CREATORDEPTCODE
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    private String creatordeptcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZLNF_ANNEX.HTTPPATH
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    private String httppath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_ANNEX.ID
     *
     * @return the value of ZLNF_ANNEX.ID
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_ANNEX.ID
     *
     * @param id the value for ZLNF_ANNEX.ID
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_ANNEX.DEPTCODE
     *
     * @return the value of ZLNF_ANNEX.DEPTCODE
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public String getDeptcode() {
        return deptcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_ANNEX.DEPTCODE
     *
     * @param deptcode the value for ZLNF_ANNEX.DEPTCODE
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public void setDeptcode(String deptcode) {
        this.deptcode = deptcode == null ? null : deptcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_ANNEX.ANNEXCODE
     *
     * @return the value of ZLNF_ANNEX.ANNEXCODE
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public String getAnnexcode() {
        return annexcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_ANNEX.ANNEXCODE
     *
     * @param annexcode the value for ZLNF_ANNEX.ANNEXCODE
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public void setAnnexcode(String annexcode) {
        this.annexcode = annexcode == null ? null : annexcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_ANNEX.ANNEXNAME
     *
     * @return the value of ZLNF_ANNEX.ANNEXNAME
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public String getAnnexname() {
        return annexname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_ANNEX.ANNEXNAME
     *
     * @param annexname the value for ZLNF_ANNEX.ANNEXNAME
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public void setAnnexname(String annexname) {
        this.annexname = annexname == null ? null : annexname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_ANNEX.ANNEXPATH
     *
     * @return the value of ZLNF_ANNEX.ANNEXPATH
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public String getAnnexpath() {
        return annexpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_ANNEX.ANNEXPATH
     *
     * @param annexpath the value for ZLNF_ANNEX.ANNEXPATH
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public void setAnnexpath(String annexpath) {
        this.annexpath = annexpath == null ? null : annexpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_ANNEX.DEPTTYPE
     *
     * @return the value of ZLNF_ANNEX.DEPTTYPE
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public String getDepttype() {
        return depttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_ANNEX.DEPTTYPE
     *
     * @param depttype the value for ZLNF_ANNEX.DEPTTYPE
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public void setDepttype(String depttype) {
        this.depttype = depttype == null ? null : depttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_ANNEX.PICTURESTYPE
     *
     * @return the value of ZLNF_ANNEX.PICTURESTYPE
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public String getPicturestype() {
        return picturestype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_ANNEX.PICTURESTYPE
     *
     * @param picturestype the value for ZLNF_ANNEX.PICTURESTYPE
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public void setPicturestype(String picturestype) {
        this.picturestype = picturestype == null ? null : picturestype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_ANNEX.ISDEFAULT
     *
     * @return the value of ZLNF_ANNEX.ISDEFAULT
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public String getIsdefault() {
        return isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_ANNEX.ISDEFAULT
     *
     * @param isdefault the value for ZLNF_ANNEX.ISDEFAULT
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public void setIsdefault(String isdefault) {
        this.isdefault = isdefault == null ? null : isdefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_ANNEX.CREATEDONUTC
     *
     * @return the value of ZLNF_ANNEX.CREATEDONUTC
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public Date getCreatedonutc() {
        return createdonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_ANNEX.CREATEDONUTC
     *
     * @param createdonutc the value for ZLNF_ANNEX.CREATEDONUTC
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public void setCreatedonutc(Date createdonutc) {
        this.createdonutc = createdonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_ANNEX.CREATOR
     *
     * @return the value of ZLNF_ANNEX.CREATOR
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_ANNEX.CREATOR
     *
     * @param creator the value for ZLNF_ANNEX.CREATOR
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_ANNEX.ISAUDIT
     *
     * @return the value of ZLNF_ANNEX.ISAUDIT
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public String getIsaudit() {
        return isaudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_ANNEX.ISAUDIT
     *
     * @param isaudit the value for ZLNF_ANNEX.ISAUDIT
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public void setIsaudit(String isaudit) {
        this.isaudit = isaudit == null ? null : isaudit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_ANNEX.ISDELETED
     *
     * @return the value of ZLNF_ANNEX.ISDELETED
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public String getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_ANNEX.ISDELETED
     *
     * @param isdeleted the value for ZLNF_ANNEX.ISDELETED
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public void setIsdeleted(String isdeleted) {
        this.isdeleted = isdeleted == null ? null : isdeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_ANNEX.MODIFIER
     *
     * @return the value of ZLNF_ANNEX.MODIFIER
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_ANNEX.MODIFIER
     *
     * @param modifier the value for ZLNF_ANNEX.MODIFIER
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_ANNEX.UPDATEDONUTC
     *
     * @return the value of ZLNF_ANNEX.UPDATEDONUTC
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public Date getUpdatedonutc() {
        return updatedonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_ANNEX.UPDATEDONUTC
     *
     * @param updatedonutc the value for ZLNF_ANNEX.UPDATEDONUTC
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public void setUpdatedonutc(Date updatedonutc) {
        this.updatedonutc = updatedonutc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_ANNEX.CREATORDEPTCODE
     *
     * @return the value of ZLNF_ANNEX.CREATORDEPTCODE
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public String getCreatordeptcode() {
        return creatordeptcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_ANNEX.CREATORDEPTCODE
     *
     * @param creatordeptcode the value for ZLNF_ANNEX.CREATORDEPTCODE
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public void setCreatordeptcode(String creatordeptcode) {
        this.creatordeptcode = creatordeptcode == null ? null : creatordeptcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZLNF_ANNEX.HTTPPATH
     *
     * @return the value of ZLNF_ANNEX.HTTPPATH
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public String getHttppath() {
        return httppath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZLNF_ANNEX.HTTPPATH
     *
     * @param httppath the value for ZLNF_ANNEX.HTTPPATH
     *
     * @mbggenerated Thu Aug 17 16:13:18 CST 2017
     */
    public void setHttppath(String httppath) {
        this.httppath = httppath == null ? null : httppath.trim();
    }
}