package com.vt.fencing.client;

import com.vt.base.mapper.IBaseMapper;
import com.vt.fencing.model.ZlnfOrderUser;
import com.vt.fencing.model.ZlnfOrderUserExample;
import java.util.List;

public interface ZlnfOrderUserMapper extends IBaseMapper<ZlnfOrderUser, ZlnfOrderUserExample, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_ORDERUSER
     *
     * @mbggenerated Fri Sep 01 09:53:11 CST 2017
     */
    int countByExample(ZlnfOrderUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_ORDERUSER
     *
     * @mbggenerated Fri Sep 01 09:53:11 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_ORDERUSER
     *
     * @mbggenerated Fri Sep 01 09:53:11 CST 2017
     */
    int insert(ZlnfOrderUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_ORDERUSER
     *
     * @mbggenerated Fri Sep 01 09:53:11 CST 2017
     */
    int insertSelective(ZlnfOrderUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_ORDERUSER
     *
     * @mbggenerated Fri Sep 01 09:53:11 CST 2017
     */
    List<ZlnfOrderUser> selectByExample(ZlnfOrderUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_ORDERUSER
     *
     * @mbggenerated Fri Sep 01 09:53:11 CST 2017
     */
    ZlnfOrderUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_ORDERUSER
     *
     * @mbggenerated Fri Sep 01 09:53:11 CST 2017
     */
    int updateByPrimaryKeySelective(ZlnfOrderUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_ORDERUSER
     *
     * @mbggenerated Fri Sep 01 09:53:11 CST 2017
     */
    int updateByPrimaryKey(ZlnfOrderUser record);
}