package com.vt.fencing.client;

import com.vt.base.mapper.IBaseMapper;
import com.vt.fencing.model.ZlnfPaymenttype;
import com.vt.fencing.model.ZlnfPaymenttypeExample;
import java.util.List;

public interface ZlnfPaymenttypeMapper extends IBaseMapper<ZlnfPaymenttype, ZlnfPaymenttypeExample, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_PAYMENTTYPE
     *
     * @mbggenerated Fri Sep 01 09:56:23 CST 2017
     */
    int countByExample(ZlnfPaymenttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_PAYMENTTYPE
     *
     * @mbggenerated Fri Sep 01 09:56:23 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_PAYMENTTYPE
     *
     * @mbggenerated Fri Sep 01 09:56:23 CST 2017
     */
    int insert(ZlnfPaymenttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_PAYMENTTYPE
     *
     * @mbggenerated Fri Sep 01 09:56:23 CST 2017
     */
    int insertSelective(ZlnfPaymenttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_PAYMENTTYPE
     *
     * @mbggenerated Fri Sep 01 09:56:23 CST 2017
     */
    List<ZlnfPaymenttype> selectByExample(ZlnfPaymenttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_PAYMENTTYPE
     *
     * @mbggenerated Fri Sep 01 09:56:23 CST 2017
     */
    ZlnfPaymenttype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_PAYMENTTYPE
     *
     * @mbggenerated Fri Sep 01 09:56:23 CST 2017
     */
    int updateByPrimaryKeySelective(ZlnfPaymenttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_PAYMENTTYPE
     *
     * @mbggenerated Fri Sep 01 09:56:23 CST 2017
     */
    int updateByPrimaryKey(ZlnfPaymenttype record);

    int queryNum(ZlnfPaymenttype record);
}