package com.vt.fencing.client;

import com.vt.base.mapper.IBaseMapper;
import com.vt.fencing.model.ZlnfLkorderHour;
import com.vt.fencing.model.ZlnfLkorderHourExample;
import java.util.List;

public interface ZlnfLkorderHourMapper extends IBaseMapper<ZlnfLkorderHour, ZlnfLkorderHourExample, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_LKORDER_HOUR
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    int countByExample(ZlnfLkorderHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_LKORDER_HOUR
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    int deleteByPrimaryKey(String bh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_LKORDER_HOUR
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    int insert(ZlnfLkorderHour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_LKORDER_HOUR
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    int insertSelective(ZlnfLkorderHour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_LKORDER_HOUR
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    List<ZlnfLkorderHour> selectByExample(ZlnfLkorderHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_LKORDER_HOUR
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    ZlnfLkorderHour selectByPrimaryKey(String bh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_LKORDER_HOUR
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    int updateByPrimaryKeySelective(ZlnfLkorderHour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_LKORDER_HOUR
     *
     * @mbggenerated Wed Oct 18 17:14:43 CST 2017
     */
    int updateByPrimaryKey(ZlnfLkorderHour record);
}