package com.vt.fencing.client;

import com.vt.base.mapper.IBaseMapper;
import com.vt.fencing.model.ZlnfFarmMachineyMerchant;
import com.vt.fencing.model.ZlnfFarmMachineyMerchantExample;
import java.util.List;

public interface ZlnfFarmMachineyMerchantMapper extends IBaseMapper<ZlnfFarmMachineyMerchant, ZlnfFarmMachineyMerchantExample, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_FARMMACHINEYMERCHANT
     *
     * @mbggenerated Fri Aug 18 11:33:02 CST 2017
     */
    int countByExample(ZlnfFarmMachineyMerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_FARMMACHINEYMERCHANT
     *
     * @mbggenerated Fri Aug 18 11:33:02 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_FARMMACHINEYMERCHANT
     *
     * @mbggenerated Fri Aug 18 11:33:02 CST 2017
     */
    int insert(ZlnfFarmMachineyMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_FARMMACHINEYMERCHANT
     *
     * @mbggenerated Fri Aug 18 11:33:02 CST 2017
     */
    int insertSelective(ZlnfFarmMachineyMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_FARMMACHINEYMERCHANT
     *
     * @mbggenerated Fri Aug 18 11:33:02 CST 2017
     */
    List<ZlnfFarmMachineyMerchant> selectByExample(ZlnfFarmMachineyMerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_FARMMACHINEYMERCHANT
     *
     * @mbggenerated Fri Aug 18 11:33:02 CST 2017
     */
    ZlnfFarmMachineyMerchant selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_FARMMACHINEYMERCHANT
     *
     * @mbggenerated Fri Aug 18 11:33:02 CST 2017
     */
    int updateByPrimaryKeySelective(ZlnfFarmMachineyMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZLNF_FARMMACHINEYMERCHANT
     *
     * @mbggenerated Fri Aug 18 11:33:02 CST 2017
     */
    int updateByPrimaryKey(ZlnfFarmMachineyMerchant record);
    
    List<ZlnfFarmMachineyMerchant> queryRownumFarm(ZlnfFarmMachineyMerchant record);
    
    List<ZlnfFarmMachineyMerchant> selectLesstanTwenty(ZlnfFarmMachineyMerchant record);

    List<ZlnfFarmMachineyMerchant> selectLesstanTen(ZlnfFarmMachineyMerchant record);
}