package com.vt.base.client;

import java.util.List;

import com.vt.base.mapper.IBaseMapper;
import com.vt.base.model.DictRelExample;
import com.vt.base.model.DictRelKey;

public interface DictRelMapper extends IBaseMapper<DictRelKey, DictRelExample, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_dict_rel
     *
     * @mbggenerated Tue Sep 01 17:50:27 CST 2015
     */
    int countByExample(DictRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_dict_rel
     *
     * @mbggenerated Tue Sep 01 17:50:27 CST 2015
     */
    int deleteByExample(DictRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_dict_rel
     *
     * @mbggenerated Tue Sep 01 17:50:27 CST 2015
     */
    int deleteByPrimaryKey(DictRelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_dict_rel
     *
     * @mbggenerated Tue Sep 01 17:50:27 CST 2015
     */
    int insert(DictRelKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_dict_rel
     *
     * @mbggenerated Tue Sep 01 17:50:27 CST 2015
     */
    int insertSelective(DictRelKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_dict_rel
     *
     * @mbggenerated Tue Sep 01 17:50:27 CST 2015
     */
    List<DictRelKey> selectByExample(DictRelExample example);
}